== Chapter III.

Visit to Ireland--Epistle to Friends in America--Visits to Scotland,
and Some Parts of England--His Sickness--Further Religious Service in England, Scotland,
and Ireland--His Third Visit to America--Religious
Engagements in Various Parts of England,
Scotland, and Ireland--His Last Illness and Death.

In the year 1698, a concern was upon me to visit Friends in Ireland.
I took shipping on the 5th of the ninth month; but meeting with a contrary wind,
was put into Ramsay bay, in the Isle of Man, where we staid some days;
then weighed anchor and got to Castletown, went on shore,
and found the people very wicked; they would scarce lodge us for our money,
because we were Quakers.
The next day we sailed to Dublin, and had three meetings there.
Then I took my journey along with Thomas Wilkinson^
footnote:["`Thomas Wilkinson resided at Beckfoot, in Cumberland.
He descended of honest parents, though not of our profession;
who dying when he was young,
he was educated by a relation in the way of the Church of England +++[+++so called.+++]+++
He joined himself with Friends in his youth,
and some time after received a gift in the ministry.
In that service, when but young, he travelled through most parts of England and Wales;
and several times visited Friends in Scotland and Ireland.
His ministry was not with enticing words of man's wisdom,
but in the demonstration of the Spirit and power;
and he was endued with an excellent gift of prayer.
As he bore a faithful testimony in word and doctrine, his conduct was agreeable thereto.
He was also zealous in his testimony against tithes: for non-payment of a small modus,
he was prosecuted in the Court of Exchequer, and suffered imprisonment sixteen years:
which suffering he bore without murmuring; and often said,
"`He never enjoyed more of the Lord's favour than in his confinement.`"
In his last illness he frequently signified that nothing stood in his way,
and that he had the full evidence of joy and peace.
He died in the year 1731, aged upwards of 78, having been a minister about 50 year.`"
--__Testimony of Cumberland Quarterly Meeting.__]
into the north, having meetings at places where none had been before;
to which abundance of people came, both English and Irish:
we laboured in the love of God among them.

At one meeting there came two priests, who appeared at first to be very light and airy;
but the Lord's power reached their hearts,
and we heard they gave a good account of the meeting.

We had a meeting at Lurgan, where there was a marriage,
to which many people came to see the accomplishment thereof.
The gospel of life and salvation was freely preached unto them; some were reached,
and turned to Christ, the true light and leader of his children.
I was much concerned for a people that knew not the Lord,
that they might be gathered unto him, and know salvation.
We travelled very hard, and had meetings every day for twenty-eight days together;
visiting people in many places where no Friends dwelt; and had good service,
particularly in the county of Derry.

We had a meeting at a place called Articelly, to which abundance of people came,
many of whom were Presbyterians;
and they fenced against the testimony that was borne all they could:
but the testimony ran so clear, that they were forced to confess to the Truth;
for our labour was to turn all to God's teaching, and to Christ the true light,
which enlightens every man that comes into the world.
After the meeting we went to Newtown-Limavady, and lodged at an inn:
the people were very hard and dark as to true religion,
being puffed up with airy notions, so that we found little place there.
Then we travelled to Dungivin, lodged at an inn,
and got a house to have a meeting in the next day but
in the morning there was a paper put upon the door,
and all people forbidden thereby to go into that house, except the king's officers.
So we kept the meeting without doors, although it was in the depth of winter;
and the Lord favoured us with his living presence,
and enabled us to preach the gospel unto the people.
Several were convinced, and many well affected, who said, Though men envied us,
yet the Lord favoured us.

From there we travelled towards Londonderry; lodged at an inn,
and had a comfortable meeting that evening.
Next day we went into the city in order to have a meeting:
many of the magistrates being Presbyterians, were very envious,
and threatened to put us in prison but we kept our meeting in the love of Christ.
The governor, several officers, and soldiers, came to the meeting,
showed kindness towards us, and restrained the rabble.
I had to warn the people to repent of their wickedness,
or else the hand of the Lord would be heavy upon them; and further to declare,
that although many families in that place had lacked bread, yet if they repented not,
many houses should have bread, and none of their family be left to eat it.
After I had delivered the message, I was eased of the weight which lay upon me,
and went away in peace.
We then travelled to a place called Cumber:
at an inn there we met with a great many Irish; one of whom was in fetters for stealing;
the power of darkness was great among them.
Next day we had a meeting appointed there, and many of those wicked people came,
and their priest, they being Papists: the Lord caused his light to shine,
and gave us his word and wisdom to divide it;
so that the gospel was freely preached to them,
and all directed to the light of the Lord Jesus Christ.
One of them was convinced of the Truth,
and much broken and tendered by the power of the Lord which overshadowed us.
The priest confessed that the doctrine he had heard that day, was true.

Then we came back to Toberhead and Charlemont, and from there to Lugganory:
we had several meetings; abundance of people flocked to them,
and we directed all to the light of Christ Jesus, the Saviour of the world;
and many confessed to the Truth.
Then we came by Melton to Dromore, a place that had not been visited by Friends before,
and had a meeting in a large room at an inn: many of the town's people came,
and it was a day of God's love to them;
they were mightily affected by the power of Truth,
and very much broken and tendered thereby: several acknowledged to the Truth,
and some were convinced.
After the meeting, we went to Hillsborough, and had a meeting there that evening,
to which several people of repute came:
one 'squire Hill was deeply affected with the testimony of Truth;
in a short time after he died.
Then we travelled to Lurgan, to the province meeting;
afterwards into the south and west parts of the nation,
where we had service in turning many people unto the Lord.
At Cork we met with several brethren in the work of the gospel:
our hearts were truly opened one to another, and glad to hear of Truth's prosperity.
After we had visited Munster, we returned to the province meeting in Leinster,
and visited the counties of Carlow, Wexford, and Wicklow.
Then finding my spirit clear, I returned to Dublin, took shipping for Whitehaven,
and at the latter end of the eleventh month, 1698, I landed safe, and' returned home,
staid some time, and was very diligent in attending meetings.

[.offset]
+++[+++The following Epistle to Friends in America,
which is not inserted either in the MS or the former edition of this Journal,
is recorded in Gough's History of Friends.]

[.signed-section-context-open]
Rogerscale, near Pardshaw, 27th of First month, 1699.

[.salutation]
Dear Friends,

In the love of God, my soul dearly salutes you all in the seed of life;
in which we are united the whole world over;
and are bound up in that one eternal Power and Spirit
by which we have been gathered to be a people,
to appear in the world to make mention of his name, and that in truth and righteousness.
All wait low in the depth of humility,
daily to feel the operation and opening of his eternal Power upon your spirits;
that by it you may be all guided in true fear and
wisdom in all your exercises and services for God,
in your several gifts and places that God has committed to your trust and charge:
that you all be showing forth the glory, and power,
and wisdom of him that has called you out of the dark world, and its ways, customs,
and fashions, into his marvellous light, to walk therein,
and to be faithful witnesses for him; and that your lights may so shine before men,
that they may see your good works, that they may glorify your Father which is in heaven.
My spirit and life is often with you,
(in my secret retirement unto the Lord,) in those remote parts of the world.

Oh! my bowels yearn towards you, night and day,
for your growth and prosperity in the Truth;
that you may be kept under the government of Christ;
where his peace will daily rise up in your souls;
which will far transcend all earthly enjoyments,
and redeem your affections out of the earth and
the snares and corruptions that are in it,
and will draw the affections heavenwards, and to seek those things that are above;
so will the Lord bless you every way, both inwardly and outwardly;
and your table will never become a trap and a snare to you.

Treasure the advice given of old, "`Trust not in uncertain riches,
but in the living God;`" and then he will abundantly bless
those parts of the world where it is your lot to dwell;
he will be as a wall of fire round about you,
and make your enemies to be at peace with you.
Keep low, there is your safety; and look not out, but to the Lord,
whose eye is watching over you for good:
and his hand is full of blessings to be poured down upon you,
if you give him not occasion to withhold them from you,
by letting your minds wander from him.
Therefore let a holy care and zeal be kept in by all,
to keep their minds close to the Lord;
so will he bring up a godly concern upon your minds, for the honour of God, and a holy,
strict discipline amongst you; that all that profess the holy Truth,
walk as becomes Truth in their life and conduct; and that those that do not,
be dealt with, and if possible be reclaimed; and if not, to clear the holy Truth of them,
and to wipe off the scandal that may be cast upon your holy profession,
by their disorderly walkings.

I do not write these things, because you know them not,
but to stir up your minds to put them in practice; and in order thereto,
we are in the practice of appointing two or more
faithful Friends in every particular meeting,
to take inspection into the conduct of Friends, how they walk as becomes Truth;
and these Friends of every meeting, (which we call a preparative meeting,
because it fits those that are appointed,) to give a true account to the monthly meeting,
that often consists of several, and takes a great deal of work from the monthly meeting;
things being done without going there.
We find great benefit in a strict discipline; and there is a great need of it.

I desire you to keep in the unity of the Spirit, which is the bond of peace;
and stir up one another to love and good works;
and that those whom God has trusted with heavenly gifts,
may all improve them to his glory.
And stir up one another to visit remote parts that need help; as Virginia, Carolina,
New England, Barbadoes, Jamaica, Antigua, Nevis, And let all be done in the love of God;
so will he bless you with spiritual blessings in his Son Christ Jesus;
in whom I dearly salute you all, letting you know I am well every way.
And to God's eternal arm of power I commit you all,
and remain your friend and brother in the holy Truth.

[.signed-section-signature]
James Dickinson.

In the forepart of the year 1699, I had drawings in my mind to visit Friends in Scotland,
and proceeded on that service in company with Jonathan Burnyeat,^
footnote:[Jonathan Burnyeat, son of John and Elizabeth,
was born in Dublin on the 4th of the eleventh month,
1686;`" consequently he was little more than twelve years of age,
when he thus united with James Dickinson in gospel service.
John Whiting in his "`Memoirs,`" towards the close of his account of John Burnyeat, says,
"`He left one son, a hopeful young man, behind him.`"
"`Jonathan Burnyeat died at Graythwaite near Crabtreebeck +++[+++in Cumberland,+++]+++
on the 5th of the third month, 1709,`" in the twenty-third year of his age.
These dates, etc., of his birth and decease,
are copied from the registers of Pardshaw monthly meeting.
{footnote-paragraph-split}
The editor regrets that he has not been able
to find further particulars respecting this extraordinary youth:
when his age is considered,
in connection with what is here said of him by James Dickinson
(see also p. 402) the reader can scarcely fail to be struck
with so remarkable an instance of early dedication;
or (while contemplating the condescension of the great Head of the church,
in committing a dispensation of the gospel to one of so tender an age,) to
regard it as an occasion which calls forth the reverent acknowledgment,
"`Out of the mouths of babes and sucklings You have perfected praise.`"]
(son of John Burnyeat,) who had the like concern.
As he was very young, and had not travelled in Truth's service before,
a concern fell upon me for his preservation every way.
The Lord was kind to us, and bore up our spirits in all our exercises.
My companion was deeply opened into the mysteries of God's kingdom; and grew in his gift,
so as to give counsel to young and old:
he was very zealous against deceit and wickedness, both in professor and profane;
and often reproved such.
We travelled together through the south and west parts of Scotland, to Douglas, Hamilton,
and Glasgow, and had many meetings among the people;
labouring to turn their minds to the Lord Jesus Christ, who is the light of the world;
warning all who professed the light to be their way, to be careful to walk therein,
that they might know their communion to increase with the Lord,
their fellowship one with another,
and the blood of Christ to cleanse them from all unrighteousness.

Then we travelled down into the north, and had many precious meetings.
From there we returned to the yearly meeting at Edinburgh,
where we met with many brethren.
Abundance of people came to the meeting, who were very rude and wicked,
and laboured to disturb us; but the testimony of Truth coming over all,
some among them were troubled, and chained down by the.
power of God.
We were deeply bowed under a sense of the Lord's favour to us:
yet under great sorrow to see the wickedness of the people.
A concern came upon Jonathan Burnyeat to write a
warning to the inhabitants of that place,
which was afterwards put in print to answer its service.
Then we travelled to Kelso, and visited Friends there; so to Berwick-upon-Tweed;
from there to Northumberland, and had meetings at several places:
many hearts were reached by the power of Truth.
Being clear, we returned home, and witnessed peace to flow in our souls.

Afterwards, finding drawings in my mind to visit several parts of England,
I began my journey on the 17th of the eighth month, 1699,
and visited Friends in Westmoreland and Yorkshire.

I was engaged to warn all in the love of Christ, to prepare for their latter end,
and to know their peace made with the Lord; for a day of trial was coming,
wherein all would stand in need of it.
I travelled through Nottinghamshire and Leicestershire, to Huntingdonshire,
where I met with great exercise with some apostates who had run out with George Keith.
They laboured to lay waste the testimony of Truth; but the Lord manifested his power,
and stood by those who were true to him, stopped the mouths of gainsayers,
and confounded them.
From there I went to the Isle of Ely, and Norfolk,
and laboured in the work of the ministry for the gathering of people to Christ,
that they might know him to be their Teacher;
and for the settling of those who were gathered;
stirring up all to their duties to God and one another.
I then returned back to Huntingdon quarterly meeting;
and was engaged to encourage Friends to come up in their several gifts and services;
and to be faithful unto the testimony God had given them to bear,
and to stand against every thing that would oppose it.
There appeared at that meeting, some very malicious,
who were bent to render Friends and their books odious;
but they were frustrated and confounded by the Lord's power,
which did eminently break forth amongst us,
whereby the hearts of the faithful became truly glad.

After the meeting I returned through the Vale of Belvoir,
and found several who were unfaithful to the Truth which they professed.
I had a warning to them to come up in faithfulness unto the Lord,
or else their latter end would be miserable; for the Lord would cast them off,
and call others who would be more faithful.
When I was clear of that place, I travelled through Derbyshire, Manchester, Mankinholes,
so to York quarterly meeting, and from there home.

Soon after my return home, I was seized with sickness;
and many concluded I could not live.
But the Lord was kind to me, by his secret hand, when in weakness of body:
and upon serious search I found nothing but peace,
and that I had got my day's work done so far.
My eye was unto the Lord Jesus, in whom my justification remained; and I found peace,
and his words true by experience.
In me you shall have peace, but in the world tribulation.
The sense of it at that time was very comfortable,
and engaged me to be given up to follow him faithfully unto the end;
for it is those that are faithful unto death, that will receive a crown of life.

Some time after my recovery, there came a concern upon me to visit some cities in England.
I took my journey on the 1st of the twelfth month, 1700;
travelled to the city of Chester, and was at their meeting:
a marriage being there that day, abundance of people came, but behaved rudely.
The word of life was livingly declared, and the testimony of Truth exalted,
whereby the unruly spirits were chained down.

I travelled through Staffordshire into Worcestershire to Worcester city;
from there to Gloucester, and so to Bristol, and visited Friends,
labouring in the work of the gospel: the word of life prevailed,
and many hearts were reached by the power of Truth.
After I had visited several parts of Gloucestershire, and had good service,
I returned home to my family; was very diligent in attending meetings,
both for worship and discipline, and visited meetings to and again in our own county.

Finding drawings in my mind to visit several remote parts in Scotland and Ireland,
I took my journey on the 15th of the eighth month, 1701;
some Friends accompanying me to the Border meeting,
where we had a comfortable season together.
I was engaged to warn Friends to be faithful to the Lord's requirings,
and keep to the conduct of his Holy Spirit,
that they might be guided in all their gifts to God's glory.
The day following Robert and Richard Lattimer went with me into Scotland,
and accompanied me several days.
As we travelled on the road to Dumfries,
I had some words of exhortation to several on the road; and some took it kindly.
We met one man (whom we passed quietly by,) who was so filled with anger against us,
that he followed me, and cried out in great rage, that I was a deceiver,
and was going to delude the people.
I stopped my horse, and asked him what he had to charge me with,
I being a stranger to him, and he to me?
But he cried.
"`Give me Scripture, or else I will not believe what you say.`"
Seeing him full of envy, I told him I had a Scripture for him, if he would hear it,
which was, "`Give not that which is holy unto the dogs,
neither cast you your pearls before swine, lest they trample them under their feet,
and turn again and rend you,`"--Matt. 7: 6;
which smote him so to the heart, that he was confounded, and left me.

When we got to Dumfries we had a meeting in the streets,^
footnote:[Samuel Bownas, who, (with his fellow-traveller in the work of the ministry,
Isaac Thompson,) was in company with James Dickinson, and R. Lattimer at this time,
makes the following mention of James Dickinson,
and of this meeting at Dumfries:--"`We went on with boldness and cheerfulness,
meeting on the way with our dear and worthy friend, James Dickinson,
who was intending a visit into Ireland.
In our journey from the Border to Dumfries, we had very profitable conversation with him,
of good service to us both; because we, by reason of youth, and lack of experience,
were often very weak; and doubting whether we were right or not in the work:
so that this dear Friend, by his tender and fatherly care and advice,
was of great encouragement, in letting us know how weak and poor he often found himself;
which so much answered my condition,
that it was as marrow to my bones.`"
{footnote-paragraph-split}
"`When we came to Dumfries,
after we had taken some refreshment at our inn, James said to us, 'Lads,
I find a concern to go into the street, will you go with me?'
For he thought it might only be to show himself,
and was desirous that we might go all together, being five in number.
So we walked forth, and the inhabitants gazed upon us,
for the Quakers were seldom seen in that town so many together: several came after us,
and James lifted up his voice like a trumpet among the people,
who were very quiet and attentive.
When he was clear, we retired to our inn, and many followed us,
who were very rude and wicked, but were not permitted to hurt us.
We had sweet comfort and refreshment one in another at our quarters.`"
--__Life of Samuel Bownas__]
where some of the people were sober, but others very rude.
I warned them to repent and turn to the Lord
while he strove with them by his Holy Spirit,
lest the day of their visitation should pass over: declaring unto them.
That the Lord was angry with the wicked every day;
and if they did not repent of their wickedness, all their talk of God, Christ,
and religion would be in vain:
for so long as people go on in rebellion against God's Holy Spirit,
and give up their hearts to wickedness, their offerings are an abomination to him;
as they might read in Isaiah, chap. 46.

After the meeting, I had discourse with several people at the inn where we lodged.
From there proceeded on my journey towards Port Patrick,
in order to take shipping for Ireland; and as I travelled through Galloway,
the states of the people were clearly manifested to me.
I spoke to them, and warned them to repent and prepare for their latter end:
several were reached and confessed to the Truth.
On the seventh-day of the week we got to Stranraer, lodged at an inn,
and staid there the first-day.

A concern came upon me to go into the streets.
I went, and the Friends along with me; we sat down in the market cross,
(it being before the door of their worship house;) and when the people came forth,
it was upon me to pray unto the Lord on their behalf.
That he would be pleased to open their understandings,
and give them the knowledge of himself, and their own states and conditions.
The priest and people came crowding about me.
Afterwards I stood up, and declared the way of life and salvation to them;
warning all to repent of their wickedness, and give up their hearts unto the Lord,
that he might purify them by the spirit of judgment and burning; "`For,`" I said,
"`until your minds are turned unto the inward manifestations of the Lord Jesus Christ,
all your preaching, praying, and singing is but vain, and an abomination in his sight,
who is of purer eyes than to behold iniquity with approbation.'`" I
directed them to the light and grace of God in their own hearts,
and to mind the operations thereof;
for it would teach them to deny ungodliness and the world's lusts, and to live soberly,
righteously, and godly, in this present world; letting them understand,
that what is to be known of God is made manifest iii man,
for the Lord has showed it unto them.
Most of the people staid until I had cleared myself of what was on my mind,
then we went back to the inn and had some discourse with the people of the house,
who confessed that what I had declared was true.

Next morning I parted with the Friends in much sweetness of spirit.
They returned home, and I travelled to Port Patrick, where I found the people very wicked.
I had an opportunity with them at a burial:
when the corpse was brought to the grave-yard, the people behaved rudely, and were vain:
but my heart was filled with the love of God,
and I was engaged in public testimony among them.
The inhabitants came out of their houses and crowded about me.
I opened unto them how they might come to the true knowledge of God; and showed them,
according to the Scripture, that He was not far from them; "`for God,
who commanded the light to shine out of darkness,`" as says the apostle,
"`has shined in our hearts, to give the light of the knowledge of the glory of God,
in the face of Jesus Christ,`"--2 Cor. 4:6-7;
and that was the true believers' treasure, and they had it in their earthen vessels.
So I directed all to Christ, the word nigh in the heart and mouth, who was to be obeyed;
and the hearts of several were reached by the power of God.

After I had cleared myself,
there came one to me and acknowledged to the Truth of what I had delivered; and said,
"`The people were rude because they had no minister in the place,
nor none to instruct them.`"
I told him they lacked the fear of God before their eyes,
and the consideration of their latter end,
otherwise they would not have been so light and vain upon such a solemn occasion.
Then the man desired me to go along with him to his house; and finding freedom, I went,
and found a woman there, who had a young child: her husband was gone over to Ireland,
and she was going, with her child, after him.
Understanding that I was a minister, she desired me to baptize her child;
and said she would pay me.
I told her, I did not preach for hire, but freely for the Lord's sake;
and as for baptizing her child, the Scriptures did not warrant me in it;
neither was I sent to baptize, but to preach the gospel,
under a sense of a necessity the Lord had laid upon me.
After some discourse, she seemed satisfied about it.

I then took boat for Ireland; while at sea we had a very high wind and much rain,
so that most on board were afraid we should be lost;
but I told them I did believe we should get safe across.
The seamen were for returning back to Scotland:
this appeared more dangerous than to continue our course for Ireland,
r therefore entreated them to keep their course; which they did,
and we were favoured to land safe at Carrickfergus the next day.
I travelled through the north part of that nation,
and had meetings where no Friends dwelt.
The Lord manifested his power, and gave me his word and strength to publish it;
so that some were convinced of the Truth.
Being clear of the north, I travelled to Dublin; was at their half-year's meeting,
and met with Friends from most parts of the nation.
We had a comfortable time together:
the affairs of the church were managed in love and condescension:
the Lord crowned our assembly with his living presence,
which bowed our hearts in thankfulness to him, the Fountain of all our mercies.

When this meeting was ended, I travelled to the province meeting in Munster;
visited that province, and had good satisfaction.
Then I returned to Leinster province meeting,
and found Friends zealous for the promotion of Truth,
and maintaining good order and discipline in the church;
which was cause of gladness to my soul.
Afterwards I was concerned to travel to many places in the province of Connaught,
several Friends accompanying me.
We had meetings at inns and in places where no Friends lived:
the testimony of Truth was freely declared and
the people directed to the light of Christ Jesus.
Some strongly opposed the Truth, and others confessed thereunto.

After I was clear of that province, I returned towards Mountmellick,
in company with a Friend.
When we were on the road, a great many Irish beset us,
and one of them knocked the Friend down with a pitchfork.
I, seeing him fall, alighted from my horse,
and helped him up from under his horse's feet,
he being bloody and not able to speak for some time.
When he was a little recovered, I spoke to one of the men who stood by,
who had set on the rest, and told him who he was,
and that they would be called to an account for what they had done.
So we went back to a house, and got the wound washed and bound up.
He not being able to travel any further, I left him there, hired a guide,
and went to Mountmellick; where I spoke to a justice,
and told him what usage we had met with on the road: he told me,
He could do nothing for us, except I would swear to it;
then he would grant me a warrant to apprehend them.
I asked if he did not believe I spoke the Truth?
He said, Yes,--but that did not answer the law: so I left him.
A little while after, the Friend recovered,
and the men were taken and punished by the magistrates.
After I was clear of my service in that nation, I returned to Dublin,
took shipping for Whitehaven, landed safe, went home and found my family well.

On the 17th of the ninth month, 1702.,
I had a concern upon me to visit Friends in the west of England, as far as Exeter;
so took my journey, and travelled through several counties.
The Lord favoured me with his living power,
by which I was enabled to answer his requirings.
I travelled hard, and passed through some danger by waters, it being winter;
and when I was clear returned home with sweet peace.
I was often concerned to attend the yearly meeting in London;
and had no greater pleasure than to feel the
Lord's heart-melting power to prevail over me,
and keep my mind in true resignation to answer his requirings.
He was graciously pleased to favour us, and reach to us by his secret Arm of salvation;
and brought us into a holy travail for the good of the churches of Christ the world over,
that the testimony of Truth might be exalted,
and every thing that would hinder the growth and prosperity of God's people subdued.
And as I gave up freely to the Lord's requirings, I witnessed peace;
which greatly engaged me to follow him faithfully wherever he was pleased to draw me.

In the year 1704, I was engaged to visit Friends in Yorkshire and Lincolnshire.
Jonathan Burnyeat had the like concern, and we travelled together in sweet brotherly love.
The Lord went before us, opened our service to us day by day,
and enabled us to answer it; so that we found great encouragement to follow him fully.
We had many meetings in these counties;
exhorting Friends to prize the day of their visitation,
(seeing the Lord had been pleased to make known his way
and Truth to them,) lest their day should pass over.
We laboured to stir up all to faithfulness to the Lord;
and to wait to know their communion and fellowship to increase with him,
and one with another,
and the blood of Jesus Christ to cleanse them from all unrighteousness.
Having finished this service, I returned to my wife and family in peace.
It was cause for thankfulness to find the secret hand of Providence attended
us both inwardly and outwardly and helped us to bear our testimony for Truth,
both in doing and suffering.

A law was now passed to recover tithes by warrant,
and Friends were thereby brought into great suffering; but the Lord was near to bear up,
and give boldness to stand in our testimony against that anti-christian yoke;
and herein we found true peace.
Many justices who were impropriators of tithes, laid heavy charges upon Friends;
and some who had very little, suffered deeply.
For a demand of three half-pence, they would often lay on ten shillings charges,
and to recover their claims, make spoil of Friends' goods.
Many of their honest neighbours were troubled that such things should be,
and would have paid for them; but Friends held their refusal to pay,
to be matter of faith and conscience, God's cause which he had entrusted us with,
and not our own;
Christ having put an end to the first priesthood and fulfilled the law that gave tithes,
and is himself a holy High Priest forever, not after the order of Aaron,
but after the order of Melchisedec.
This being our faith, for which many Friends had suffered,
and laid down their lives in nasty jails,
we could not accept of this offer to pay for us,
lest we should make shipwreck of faith and a good conscience,
and lose our peace with God.

Great was my exercise many times for the promotion of Truth's testimony,
and in standing against that which caused it to suffer.
About this time there appeared some in our county very
hot and zealous for order and discipline in the church,
and busied themselves in church affairs.
I saw they were going into Ranterism, and told Friends of it,
desiring that endeavours might be used to help them, which was done;
but they refusing to take advice, ran out into strife and contention,
and became bitter opposers of Friends and Truth, to their own irreparable loss.
My spirit was deeply afflicted, and under great exercise; but I could not help them.
The Lord showed me it was a false birth, begotten in them by the power of darkness,
and that all who joined with them would be hurt;
but that they should proceed nu further than to manifest their folly.

I had many journeys on the account of the testimony God had given me to bear;
for whenever I found the Lord to draw me forth, I gave up in obedience thereunto.
My dear wife was a true helpmate to me, and never hindered me at any time;
but often desired me to mind my service, and answer it;
and let all other concerns give way to Truth's concerns.
We found godliness was truly "`profitable unto all things,
having promise of the life that now is, and of that which is to come,`" life everlasting;
so that we were encouraged to follow the Lord fully,
and keep to his eternal power that had prevailed over us.
And the more our eyes were kept to him,
the greater necessity we found of the help of his Holy
Spirit to keep us in our way heaven-wards;
knowing without him we could do nothing, and seeing our own infirmities to be great.
But as we kept to the light and guidings of his Holy Spirit,
we witnessed his strength manifested in our weakness;
so that we were made to magnify that Arm which is strong,
and as near to help his people as ever.
Those who are alive to God know it; and the reason why people know it not, is,
because they do not turn to and mind the manifestation
of the light of the Lord in themselves,
and come to walk in it; for "`to as many as received him,
to them gave he power to become the sons of God,
even to them that believe on his name.`"--John 1:12.
God is still faithful in fulfilling his promises;
and whatever they ask in his name, he gives them:
such are bound in duty to return to him thanksgiving and glory, who is worthy thereof.

I had a concern, for several years, to visit Friends a third time, in America;
and understanding my ancient companion and fellow-labourer in the gospel, Thomas Wilson,
had a concern for that land, I wrote to him, and we agreed to meet at Dublin.
I acquainted my brethren with what I had upon my mind;
and they having unity with me therein,
our hearts were broken and tendered before the Lord,
and our prayers were poured forth unto him for one another's preservation.
I agreed with Richard Kelsey of Whitehaven, for my passage;
and on the first-day of the week, I, with my dear wife,
went to our own meeting at Pardshaw-Cragg:
there I received notice that the master had ordered all
his men to be on board by the tenth hour at night,
intending to sail that tide.
We had a blessed, heavenly meeting; after which I went to Whitehaven,
my wife and several Friends accompanying me.
We alighted at an inn, and had a sweet opportunity together;
then went down to the ship-side, where I parted with my wife and Friends,
(except John Robinson and Joseph Steel, who in pure love,
accompanied me to Dublin) in much bowed-downness of mind before the Lord,
in a sense of his love that had prevailed over me to answer his requirings;
in which I found my peace to flow abundantly.
Then I went on board, and in two days' time arrived at Dublin,
where I met with my dear companion, Thomas Wilson, who was ready to embark with me.
We staid two weeks in Dublin, had a comfortable time among Friends,
and parted with them in much love and tenderness.

On the 8th of the tenth month, 1713, we sailed for Virginia.
The wind being southerly, we stood down the North Channel,
and in three days' time got clear of the land: but soon after,
we met with a hard gale of wind, and were driven to the northward, near Greenland;
so that we got but little on our voyage for several weeks.
The master was very diligent and careful in the ship, and among his men,
and respectful to us.
He being a serious, thoughtful man, we had much discourse with him about religion;
and he was several times reached by the power of the Lord, and confessed to the Truth,
The Lord was kind to us, filled our hearts with his love,
and sweetened our exercises when upon the deep ocean.
The wind favouring us, we got well into Lynhaven bay within the capes of Virginia,
that day nine weeks we lost sight of Ireland;
then sailed up Chesapeake bay into Rappahannoc river,
and went on shore at Queen Anne's town, on the 14th of the twelfth month,
where we parted with our kind captain in great love.
He spoke to us to take some of our provisions along with us, and gave us loving counsel;
which counsel we took kindly.

After we landed, we found the people seemingly kind,
went to a house and refreshed ourselves: from there we hired horses to York river.
Next day we got over to the western shore, took our saddles, bags, and great coats,
upon our shoulders, and travelled several miles: then met a man who knew me,
and said he had best alight and take our things upon his horse; which we kindly accepted.
So he went along with us to James Bates's house, who received us gladly.
It being their week-day meeting, we went along with them,
though we were very weary with travelling; yet the Lord remembered us in mercy,
and we had a comfortable meeting with the few Friends there.
Then we travelled through Virginia to North Carolina, and had many good meetings,
both among Friends and others.
Truth was manifested, and the gospel of life and salvation freely declared;
and we were comforted with our brethren.

In Carolina we found a hopeful stock of young people,
whom the Lord was qualifying for his service;
and they received the testimony of Truth with gladness:
we also met with several who had been convinced when we laboured in these parts before;
and it was a great comfort to us to find them walking in the Truth.

After we were clear, we returned back to Chuckatuck, where we had a precious meeting;
then travelled towards Nancemond, and had good service:
after which we visited Friends up James river, and so returned by Black creek,
and had several meetings.
We directed the minds of people unto the Lord Jesus Christ,
and to the blessed teachings of his Holy Spirit,
which we found at work in the hearts of several, which was cause of gladness to us.
Then we passed over Potomac river, travelled late, and got to a justice's house.
He kindly invited us to stay all night, which we did,
and had some religious discourse with him; he was very friendly,
and confessed to the Truth.
Next day we passed over Patuxent river,
and visited Friends on the western shore of Maryland;
where we found great openness both among them and others.
From there we crossed the bay to the eastern shore, several Friends accompanying us:
we travelled to Salem, in Jersey, having many glorious meetings,
the Lord's good presence still attending us; and we staid the yearly meeting at Salem,
which was large and to satisfaction.
After we visited the meetings on that side of Delaware river,
we passed over to Philadelphia, and visited Friends in that city:
the Lord's power was witnessed in our assemblies,
and the doctrine of Truth largely opened.
From there we travelled to Germantown,
and visited the meetings of Friends in Pennsylvania,
some of which were the largest I had ever been at: people flocked so to them,
that several hundreds were forced to stand without doors,
the meeting-house not being large enough to contain them.
We preached unto them the doctrine of Truth, whereby the hearts of several were reached.
Then we crossed over the river Delaware again, and visited Friends in the Jerseys,
After which, we took boat at Woodbridge for New York; from there to Flushing,
and so to the yearly meeting in Long Island, which began the 30th of third month,
and held four days i it was very large,
and we had a good opportunity among Friends and others.
Friends were in sweet unity,
and the affairs of the church were managed in true brotherly love.

Being pressed in spirit to be at the yearly meeting at Rhode Island,
we took shipping and arrived at Newport, the day before the meeting began.
The universal love of God was held forth to the people,
and many hearts were reached and tendered thereby.
After the meeting, we travelled to Taunton,
and had a meeting there among the Presbyterians:
many came and were generally well satisfied; several were reached, and some convinced;
and a meeting is since settled there.
From there we travelled to Dartmouth:
and finding a concern on my mind to go to the yearly meeting at Nantucket,
I left my companion and took ship for that island.
We were in some danger in passing through Woodse's Hole,
which had a great many rocks in it; but having a fresh gale of wind, we got well through;
the vessel struck ground several times, yet went off again without damage.
Many of the inhabitants came to the meeting: the gospel was freely preached,
and all directed to the Lord Jesus Christ, and to the word of his grace,
that is still able to keep from evil,
and give them a place among them that are sanctified.
The people were generally sober, and some were convinced.

Being clear, I took shipping for Dartmouth; but meeting with a contrary wind,
got to a harbour:
and understanding there would be a meeting the next day at a Friend's house,
about eight miles distant,
I left the vessel and travelled along with the Friend to Daniel Butler's house,
and staid there all night.
Next morning went along with the Friends to the meeting: many sober people came,
the testimony of Truth was declared, and the Lord's power witnessed to our comfort.
After the meeting, I proceeded to Sandwich, where I met with my companion.
We travelled through the country to Boston,
and had some meetings to satisfaction as we went.
At Boston we had several meetings; the testimony of Truth was declared,
and the way of life and salvation manifested;
and several were reached and affected thereby.

From there we went to Lynn, Salem, and the eastern parts of New England,
and as far as Dover;
setting forth to the people that the love of God was
extended unto them in order for their salvation.
The priests were enraged against us,
and laboured to keep the people from coming to our meetings; but Truth prevailed,
and abundance of people flocked to hear the gospel preached;
so that several were convinced, and the mouths of gainsayers stopped.

After we had cleared ourselves there,
we returned back to Boston and had several meetings: Truth prevailed,
many hearts were affected, and several convinced.
From there we travelled to the yearly meeting at Providence:
there came several rude and disorderly persons;
but we warned them to repent of their wickedness and turn to the Lord.
The power of the Lord came mightily over the people, and we had a glorious,
heavenly meeting.
From there we travelled to Rhode Island, and had several meetings in our way.

After our service was over in that place, we parted with Friends,
and returned by water to Long Island;
being desirous to be at the yearly meeting at Burlington,
which is held there for West Jersey and Pennsylvania.
We took shipping at Newport, and were nine days at sea; had a meeting on board,
and had several opportunities to vindicate our principles:
some were reached by the Truth.
We landed at Flushing, had a meeting there, and several more on the island:
abundance of people attended them; the Lord's power was eminently witnessed,
and the hearts of the faithful truly comforted.
From there we went to New York, several Friends accompanying us;
and we had a precious meeting there: then crossed over to Elizabeth-town by sea;
so travelled to Woodbridge and had good service there:
many hearts were reached by the Truth, and some convinced.
Then we travelled through Jersey to Pennsylvania again,
where we met with John Salkeld and John Wright at the Falls meeting,
who were travelling in Truth's service.

The next day, we were at their quarterly meeting,
and encouraged Friends to keep to the good order established among us; the Lord owned us,
and filled our hearts with love to him and one another.
After the meeting, we travelled towards the wilderness,
and visited Friends in North Wales: we had several meetings in the country thereabouts,
and many were reached and convinced of God's blessed Truth.
At Nottingham we had a large and heavenly meeting; it was held in the woods,
because the house was not large enough to contain the people.

From there we came back by way of New Garden, were at a marriage there,
and had good service in opening to the people the way of life and salvation;
and showed them it was the Lord that joined people,
and not the work of any priest under the law, nor minister under the gospel,
but the parties concerned by consent; and those that were present were witnesses,
as in the case of Boaz and Ruth: the Lord owned us, and Truth came up into dominion.

We travelled to Philadelphia, took boat and went to Burlington yearly meeting;
where the Lord owned us with his living presence, and we had a glorious season together.
The meeting held five days;
and there was such a concourse of people that we had two meetings at once,
one at the court-house, and the other at Friends' meeting-house.
The affairs of Truth were managed in love and meekness, to the edification of the church.
We parted in love, returned to Philadelphia, and visited the outcorners of Pennsylvania.
Afterwards we proceeded to the yearly meeting on the eastern shore of Maryland,
which held four days: we had good service and came away in peace of mind.
Then we visited the lower counties of Pennsylvania, where we had many precious meetings,
and several were convinced of the Truth.
We returned again to Philadelphia; and after some stay in and about that city,
we parted with Friends in the love of God, travelled down to Oxford, in Maryland,
and agreed with the master of a vessel for our passage to England:
but not being fully clear, we were desirous to have staid a little longer.
The master told us, his signal for sailing should be the firing of a gun,
and so we might stay till then;
but we were called on board before we had quite gone through our service.

On the 7th of the ninth month, 1714, we took shipping at Oxford;
and within two days after we set sail, the ship sprung a leak.
We were greatly exercised in our spirits, and treated with the captain to return back,
in order to get the leak stopped;
but he and the rest of the officers resolved to proceed on their voyage.
The wind being contrary, they could get little forward, but rode at anchor;
in which time we told the captain,
it appeared to us that divine Providence had put the opportunity into his hand,
whereby he might save his own life, and all that were with him, and the ship too.
When we had got about twenty leagues from the land, we were becalmed;
and the leak increased so, that she made near two feet water in half an hour;
then they all repented that they did not take our advice.
We were deeply exercised, and poured forth our prayers unto the Almighty;
who was graciously pleased to grant our petition,
and caused a gentle south wind to blow the next day;
and the leak stopped so as the pumps kept her clear;
and after some difficulty we got to an anchor in Lynhaven bay.

We went on shore the 25th of the ninth month, and the next day got among Friends.
They were glad to see us;
and our hearts were deeply thankful to the Almighty for so signal a preservation.
We laboured in the work of the gospel at Nancemond,
where several hearts were thoroughly reached by the penetrating power of God.
After which, we visited several places remote from the body of Friends;
then crossed James river, and visited Friends in York county; we had several meetings,
to which abundance of people came: the doctrine of Truth was declared,
and several convinced, which was cause of gladness to us.
From there we travelled into the county of Kent,
where we had laboured in the work of the ministry twenty-three years before:
several were then convinced, and a meeting settled from that time.
We rejoiced to find people gathered to God;
and we had many precious meetings in those parts.
We travelled next into the county of Westmoreland; had good service there,
and found great openness among the people: several were convinced of the Truth,
the mouths of gainsayers were stopped, and the testimony of Truth exalted over all.
Then we found our hearts engaged to visit Friends on the western shore of Maryland;
so travelled to Potomac river, which we got over with some difficulty and charge;
being willing to spend and be spent to answer the Lord's requirings;
who had been kind to us and his people, in blessing us both inwardly and outwardly.
Friends were willing to accompany us; and we were truly thankful unto the Lord,
that he had raised up a people, and made them willing to serve him:
for when we travelled in those parts in 1692, we had no guide for a hundred miles,
and lay out in the woods; yet we travelled in faith that the Lord would spread his Truth,
and exalt it in the earth.
We saw it fulfilled in part; and firmly believe that he will carry it on to his own glory.
We took our journey through the woods, and lodged at a poor man's house that night.
We gave him money for his kind entertainment: he told us he had entertained many,
but never had taken anything before:
we told him we were not willing to be chargeable to any, but would freely pay him.

We travelled to Patnxent river, and had a meeting on the first-day:
it was a day of visitation to the youth, whose hearts were opened by the love of God,
in which we laboured to turn their minds to his teaching.
We made a thorough visit on the western shore:
many flocked to our meetings and heard the gospel freely declared,
and the principles of Truth laid open: several were convinced,
and the faithful comforted in the Lord.
Then we passed over the river to the eastern shore, and had a meeting;
to which abundance of people came, that were not Friends.
The Lord appeared to our comfort, and we had good service in many places in those parts.
Being clear of that shore, several young men got a boat, and set us over the bay.
It being very foggy, we landed at Sharp's Island, and went on shore:
the young men made a fire near the boat, and lay by it all night;
my companion and I went to a house upon the island,
where we staid until the next morning.
The people were very loving, and would take nothing for our bed.
Then we took boat,
and through some difficulty got to West river and had several meetings among Friends:
we laboured in the love of God, to settle them upon Christ, the Rock and Foundation.

After which, finding our spirits fully clear, we concluded to take shipping for England.
There being a ship bound for London, we agreed for our passage;
went on board on the 10th of the twelfth month, 1714, and on the 17th of the same,
weighed anchor, and came out of the capes of Virginia,
We had a good passage till we came near the coasts of Ireland,
where we met with a small ship bound for Cork:
we left the ship we were in and went on board the small vessel.
Afterwards we met with a contrary wind, and were seven days at sea;
then landed safe at Cork, on the 30th of the first month, 1715.
We staid a meeting with Friends at Cork, and the Lord's power was manifested among us;
his love melted our hearts,
and prepared sacrifices of praises to the God and Father of all our mercies,
who with his dear Son, is worthy thereof.

After the meeting, we took our journey towards the province meeting at Mountmelick,
and with hard travel got there on the first-day.
Friends were settled in the meeting before we went in:
the Lord's power overshadowed the meeting in a wonderful manner,
so that we were sweetly comforted together.
After this meeting, I parted with my dear companion, Thomas Wilson, in the love of God,
and went with Friends to Dublin, The next day, had a meeting to satisfaction:
after which I took shipping, sailed that night, and landed next evening at Whitehaven,
and was at our own meeting at Pardshaw-Cragg;
where Friends were glad to see me returned safely from so long a journey;
and we were comforted in the Lord and one another.

In all this voyage and journey, we were highly favoured with health for the most part,
and way was made for us far beyond what we could expect;
having travelled by sea and land about 12,000 miles.
At my return home, I found my wife and family well, for which I was truly thankful:
the Lord who separated us for his name sake,
brought us together again to our great comfort; which caused us to admire his goodness,
and to bless his most worthy name.

I staid but a few weeks at home before I took my journey for London;
having drawings in my mind to be at the yearly meeting there.
I travelled to Yorkshire, and had several meetings as I went along,
which were to the satisfaction and comfort of Friends.
I got to London the day before the meeting began,
and met with several brethren from Ireland, and most parts of this nation.
The Lord crowned our assemblies with his living presence,
and filled our hearts with the joy of his salvation.

In the year 1717, I passed through various exercises,
yet the Lord's power supported and enabled me to stand
in my testimony both in doing and suffering.
A concern increased in my mind for the peace and welfare of the church,
and that every thing might be kept out which would hurt the
growth and prosperity thereof We were greatly exercised in our
county with many filthy and unclean spirits;
and much abused by them both in meetings and out of meetings,
I went to the yearly meeting for the northern counties, held at Chester,
which was to the satisfaction and comfort of Friends.

On the 29th of the third month,
I took my journey from my own house to the yearly meeting in London,
and had service at several places on the road,
I got to London the night before the meeting began,
and met with brethren from several parts of this nation and Ireland.
The meeting was large; and Friends were zealously concerned for the prosperity of Truth,
and that every thing might be kept out of the church which
would hinder the growth thereof We had many precious seasons,
and were comforted in the Lord.

After the meeting, I was engaged by the love of God,
to visit several parts of this nation.
At Reading, Friends were under a great exercise with a rending, dividing spirit,
that many were betrayed into; yet the Lord's power came over them,
and they who had gone out into separation,
left their meeting and returned to Friends again.
My travail among them was.
That all might be baptised down, as into the bottom of Jordan,
there to be purged from their uncleanness; and so be fitted for the camp of God,
and know him to tabernacle with them.
The Lord's power was manifested among us, to the comfort of all who truly loved it.
Then I travelled to Newbury; and through Wiltshire to Bristol.
My exercise was.
That all might be sensible of the work of the
Lord to sanctify and fit them for his kingdom.
I saw the fields ripe unto harvest, which was great,
and the faithful labourers therein were but a few; my cries went forth unto the Lord,
That he would fit many, and send them forth into his harvest.
He was near to answer and to bow the spirits of many under the operation of his hand;
of which I was glad, under a sense of his great love to mankind.
After I was clear of that city, I returned homewards; visited many places,
and had good satisfaction.

Having some drawings to visit Friends and others in Northumberland and Durham,
on the 11th of the eleventh month, 1717, I took my journey and went to Wigton;
and was exercised with some ranting spirits: yet the Lord's power came over them,
and the faithful were comforted.
Then I travelled to Carlisle, and from there to Alstone,
where I found several who were convinced of the Truth,
and brought forth in public testimony: it was cause of gladness to me,
thus to behold the Lord's work to prosper.
A tier which I passed on through Allondale, where I found some young people convinced,
and hopeful to do well.
Then I travelled to Newcastle, and warned people to give up their hearts unto the Lord.
From there I went to Shields and Sunderland, where I met with Thomas Story,
who was travelling upon Truth's account,
and had been above three years from his own habitation;
having visited Friends in America, and many parts of England, Wales, Holland, Scotland,
and Ireland.
I was glad to see him, and to hear of the prosperity of Truth in those parts.
After which, I proceeded on my journey to Stockton, Darlington, Auckland, and Raby,
visiting Friends; and being clear I returned home.

Some time after my return, I went to our quarterly meeting at Carlisle;
and so to the yearly meeting at Kendal, which was large.
Several people of other persuasions came into the meeting, who were sober and attentive,
and pretty much affected with the testimonies that were borne: the meeting ended well,
and to good satisfaction.

On the 17th of the third month, 1718,
I took my journey for the yearly meeting in London along with Peter Fearon.
We had several meetings as we went;
and in London we met with Friends from several parts of this nation and Ireland,
who were come to attend that meeting.
We laboured together for the good of the church; and the Lord was with us,
and enabled us to go through our respective services to his glory,
and our mutual edification.
After the meeting I returned home to my family, and found peace;
as I always did in answering that service I believed the Lord required of me.
When I was at liberty I laboured diligently ia my outward business,
not only because of the benefit I received therefrom,
but that I might be exemplary among my neighbours.

A concern having been upon my mind for some time, to visit the western parts of England,
I took my journey on the 2nd of the ninth month, 1718,
and visited several counties as far as Bristol, and had service in that city:
after which I travelled into Devonshire; then returned to Bristol,
and from there I travelled through Wiltshire, by way of Reading to London.
After some stay in and about that city, I returned home,
having had many precious meetings among my brethren.
My labour and travail was, to encourage the faithful, stir up the backward,
and warn the wicked to repent, and turn to the teachings of the Lord Jesus Christ.

Finding myself engaged to visit Friends in the nation of Ireland once more,
on the 23rd of the eighth month, 1722, I set forward on my journey,
and went to David Hodgson's +++[+++near Carlisle,]
in company with several Friends.

Next morning we met John Urwen,^
footnote:["`John Urwen was born at Parkrigg, in the north of Cumberland.
He was educated in a sober, religious manner,
and was favoured with the visitations of divine love in his early years,
whereby he was engaged to seek the Lord, and to love him above all.
About the twenty-eighth year of his age, he was called to the ministry.
His testimony for some time was not large, but very edifying and acceptable:
and as he kept in pure, humble dependence upon the Lord, he improved in his gift greatly,
and, in due time became a truly evangelical minister.
He was often in those small meetings of his own neighbourhood,
powerfully engaged in the ministry; also in fervent supplication,
in which he was favoured with near access to the Almighty.
His services in the discipline were likewise weighty;
for being a man of great natural abilities, and those sanctified,
and made subservient to the Truth, he became singularly eminent in the church.
He repeatedly visited Friends of this nation, Scotland and Ireland.
In the latter part of his time,
Divine Wisdom permitted him to be deeply tried in various respects:
he went through evil report and good report: but the Lord was with him,
enabling him to bear all with calmness and Christian fortitude,
and to persevere faithfully many years after,
both in the ministry and the discipline of the church.
Some time before his departure he said, that nothing stood in his way;
and that if he had his life to live over again, he did not well know how to do better.
He died at Mosside, in Cumberland, in the year 1762, aged about 86,
and a minister 58 years.`"--__Testimony of Carlisle monthly meeting.__]
(who had the like concern with me,) at Allason's Bank in Scotland;
and proceeding to Dumfries we lodged there.
Next morning the Friends who came to accompany me returning home,
we continued our journey, and found the people high in notion,
and bent against the Truth, which occasioned us to mourn before the Lord.

We then went to Baldown to William Boyges's,
and had a comfortable meeting there on the first-day.
The day following we travelled to Port Patrick, where we staid some time,
(the wind being contrary,) under great exercise of spirit,
because of the wickedness of the people.

We had a meeting among them at a widow's house where we lodged,
and the gospel was freely preached unto them; some were affected therewith,
and confessed to the Truth, which filled our hearts with thankfulness unto the Lord,
who made way for us to clear our consciences among them.
On the first-day of the week my companion had a
concern upon him to go to their worship house,
and I found it my place to go with him.
After the priest had done,
my companion stood up to clear himself of what was upon his mind; but the priest,
contrary to his promise, that 'he should be heard,' went out,
and ordered all the rest to follow him, or else the door should be locked:
so they all came out, and we found ourselves clear, and came away in peace.

Next day we took boat for Ireland, and had a great storm at sea,
and were in danger of being cast away; but the Lord preserved us,
and we arrived safe on shore; and went next day to Lisnagarvy,
where Friends were glad to see us.
We travelled through the north, and had many precious meetings.
After we were clear of the north, we proceeded to Edenderry, visiting meetings all along;
labouring in that ability God gave us, for the stirring up of all to faithfulness.
We went from there to the province meeting at Carlow.
After our service there, we travelled into the counties of Wicklow and Waterford,
and had many blessed seasons in those parts;
labouring to gather people to God's teaching, and to turn them from that of Satan.

Then we travelled to Ross, and through several places to the province meeting at Cork,
which was large.
The affairs of the church were carried on and managed in the peaceable spirit of Christ,
and the meeting ended well.
After which we visited Friends in the county of Limerick;
then travelled to the province meeting at Mountmelick;
and from there to my former dear companion Thomas Wilson's,
and were sweetly refreshed together in the enjoyment of God's love.
We parted with him in much tenderness at Edenderry, travelled to Dublin,
and had some service there.

Finding ourselves clear of that city we took shipping for England.
On our voyage we had a great storm, and cast anchor in Ramsey bay.
The wind was so strong that we could not raise our anchor, and in the night,
another ship was driven upon the bow of ours;
our bow-sprit got between her main-mast and mizen-mast,
and she was like to have driven us from our anchor; but our men cut their mizen-shrouds,
and we got clear one of another, which was a great mercy; for had it been otherwise,
we might all have perished.
Thus the Lord's arm was made bare for our help;
and we landed safe at Parton in Cumberland.
The next day, I parted with my companion, returned home and found my family well.
Thus was I brought under renewed obligation to return
praise and thanksgiving to the holy name of the Lord,
who had helped me through my travels, been with my dear wife,
and brought us together again, with an increase of peace in our bosoms.
I staid at home some time, and was very diligent in attending meetings,
and visiting Friends to and again in our county.

After this, a concern came upon me to visit Friends in the west of England.
My wife at this time being under great weakness of body, I was unwilling to leave her;
but she bid me answer what the Lord required of me,
and not let anything hinder my service; tor life is in the hand of the Lord,
and he can give or take away at his pleasure.
So I gave up to the Lord's requirings, in which I witnessed peace.
I set forth on my journey with William Dixon,^
footnote:["`William Dixon, resided at Waterend in Loweswater, Cumberland.
He was descended of believing parents, and educated in the way of Truth.
It pleased the Lord to visit him in his tender age,
and he freely gave up to follow his leadings.
About the twenty-first or twenty-second year of his age,
he came forth in public testimony; and being faithful to the gift bestowed upon him,
he grew and became very serviceable.
He travelled pretty much in his early coming forth, into most of the adjacent counties,
as also in some western counties.
He was rather backward in appearance; but his doctrine was sound,
and often dropped as the dew, and distilled as the rain on the tender plants;
and he was very fervent in his approaches in prayer.
He was of a weakly constitution, and about the thirty-sixth year of his age,
fell into a decline.
During his illness, among other sweet expressions he said,
'I am satisfied when this poor body goes to the dust,
there is a place of rest prepared for my soul.
Oh! it is good to make use of time.
I rejoice that I die in unity with my friends, and that the Lord is now near me.'
He died in the year 1734, and thirty-seventh of his age.`"
--__Testimony of Cumberland Quarterly meeting.__]
a Friend of our meeting, who had the like concern with me.
We travelled through Lancashire, and the west parts of England, as far as the Land's end:
our labour was, to turn people to the Lord, and settle them on his teachings.
We found an openness in many places to receive the testimony of Truth,
for which we were truly thankful: after which, finding ourselves clear, we returned home.

On the 2nd of the tenth month, 1726, I set forward on my journey,
and William Dixon along with me, to visit Friends in Yorkshire.
We had a meeting at Soulby, among some people who had been hurt by a wrong spirit,
and were gone into separation from Friends;
yet we found the reaches of the love of God unto them,
and several hearts were touched therewith.
We went to Penrith that evening, and had a meeting there,
to which several of the Separatists, and abundance of other people came.
The Lord's power was manifested, and the testimony of Truth declared:
we directed them to the light of the Lord Jesus Christ which shines in their hearts,
in order to give them the knowledge of God, whom to know is life eternal.
Many hearts were reached,
and we had the answer of peace for our labours of love among them.
After which we went to Strickland and had a meeting there, which was to satisfaction;
and from there to Swaledale, Richmond,
and several parts of Yorkshire to the quarterly meeting at York,
where we met with John Salkeld, who was come from America to visit Friends in England.
At this meeting I laid before Friends the necessity there was
to take care to preserve the accounts of Friends' sufferings,
and of their exercises and deep trials they had undergone for
the testimony the Lord had given them to bear:
and how he had made manifest his eternal power for their help,
and wrought wonders for their deliverance;
that those accounts might be serviceable to future generations;
and the quarterly meeting took notice of it,
and agreed that it should be offered to the yearly meeting in London.
I had offered the same to our quarterly meeting in Cumberland,
which meeting agreed with me.
Afterwards we travelled to the quarterly meetings at Lancaster and Kendal;
both of which meetings agreed with me in my proposition
for collecting the accounts of Friends' sufferings.
Then being clear of what was upon our minds, we returned home, and found things well,
which was cause of gladness to me.

After I had staid some time at home,
I took shipping at Whitehaven for the half-year's meeting at Dublin,
at which meeting I offered the concern which was upon my mind,
for putting Friends' sufferings in order for future service.
The meeting took it under consideration,
and became zealously concerned that care might be taken
for preserving the records of Friends' sufferings,
for the benefit of future ages; that they might know how the Lord had raised up a people,
who were no people,
to bear testimony to his name and Truth upon earthy not only to believe,
but also to suffer for it.
After the meeting was over, I returned home.

In the year 1727, I travelled to the yearly meeting at Chester, which was large;
and many testimonies were borne, directing all to the Lord's teachings:
after which I travelled through several counties to the yearly meeting at Bristol;
still labouring in that ability God gave me,
to gather people to the teachings of his Holy Spirit.
From there I travelled to the yearly meeting in London;
and laid the concern which had been upon my mind for some time,
about collecting and printing an account of the
deep sufferings which Friends had undergone;
that they might be transmitted to future ages,
for a testimony of the great favours and mercies of God to his faithful people.
The meeting saw it was necessary, and the same was soon after proceeded upon.
Then I got ease of the concern which had been so long upon me.
After the meeting was over, visiting some meetings in my way,
I returned home and found things well; for which I was made humbly thankful to the Lord,
who provided for me both inwardly and outwardly; blessed be his holy name forever.

[.asterism]
'''

And thus ended, as far as appears, the writings of this worthy man;
for after the year 1727 we find no account,
though he travelled several times to the yearly meeting in London,
and through many parts of this nation;
but being seized about that time with a paralytic disorder,
that might probably be the reason that he committed no more to writing.

In the year 1726, his wife died, which was a great loss to him,
(his bodily infirmities considered;) but he bore it with patience,
and resignation unto the divine will, believing it was her great and everlasting gain.

He was very constant in attending the quarterly meetings in this county,
and also the meetings for worship and discipline he belonged to,
even when under great weakness of body;
which is a convincing testimony of his steady
and unshaken zeal for the promotion of Truth,
and the good of souls.

About a year before his death, his distemper, the palsy,
increased upon him to such a degree that he lost the use of one side,
and his speech was in a great measure taken from him; yet he had small intervals,
in which he seemed to surmount the decays of sinking nature,
and appeared in a sweet and heavenly disposition of mind;
intimating that his day's work was done; and that God, whom he had served,
was still with him;
that he had the evidence of peace and future felicity sealed upon his soul,
and was only waiting to be removed;
but was fully resigned unto the Lord to wait his time:
and leaning upon the divine Arm of consolation,
his afflictions and exercises became more easy to him.

He departed this life on the 6th day of the third month, 1741,
and was buried on the 8th of the same, at Friends' burying-ground at Eaglesfield,
in the county of Cumberland.
