[#pardshaw-testimony.style-blurb, short="Testimony of Pardshaw Meeting"]
== The Testimony of Pardshaw monthly meeting concerning our worthy Friend, James Dickinson, deceased.

James Dickinson of Greentrees (otherwise Moorside,) belonging to Pardshaw meeting,
in the county of Cumberland, was born at Lowmoor, of honest parents, in the year 1658.

The Lord was pleased tenderly to visit him in his young years,
whereby he became acquainted measurably with his teachings when but a child;
but for lack of keeping a steadfast eye to the guidings thereof,
was led forth into those follies and vanities of the world incident to youth.
But such was the love of the heavenly Father,
(as he often declared amongst us in the spring of the gospel) that he was met with again,
and brought back as a sheep strayed from the Father's fold;
and after much affliction and solitary exercise, was fitted for future service;
and engaged in a public testimony about the eighteenth year of his age.
He was shortly after concerned to go to several meetings of
the dissenters in the country where he lived,
and underwent hardships among them; yet Truth crowned his labours with some convincement.
After which he travelled in the service of the ministry,
in several counties through England, Ireland, and Scotland;
undergoing sufferings in the times of persecution.
He visited Friends in Ireland twelve times, three times in America,
once in Holland and Germany,
and laboured much in his native country and nation of England,
many having been convinced by him.
Much more might have been said concerning his
labours and travels in the work of the ministry,
but we refer to the preceding journal.

We have this testimony to give concerning our dear deceased Friend:
he was a diligent labourer at home, a constant attender of meetings,
a sincere travailer therein, very tender over the youth, a nursing father to the least,
and full of charity to all rightly anointed; yet not hasty to join with forward spirits.
He was also careful not to join in party causes,
but was greatly concerned for the promotion and unity of the church;
and often expressed his steadfast faith of Truth`'
s testimony being exalted in the nations,
and the anti-christian oppression of tithes brought down;
and with concern declared his sorrow for such as weakly complied therewith.

When, his natural abilities failed, he would speak strongly,
apparently beyond his age and constitution.
He was seized with a palsy near a year before he died,
which detained him from coming to meetings,
and by which his speech was much taken from him; but he would often say.
Though he was weak, he was well, and had nothing but peace on every hand;
expressing his care and concern for the growth and preservation of the church.

He died on the 6th of the third month, 1741, and was interred on the 8th of the same,
in Friends`' burying-ground, at Eaglesfield,
being accompanied by a great many Friends and others.
Aged eighty-three, a minister sixty-five years.

Read, approved, and signed, at our quarterly meeting, held at Pardshaw Hall,
in the county of Cumberland, the 1st of the second month, 1742, By John Wilson.
