[#bell-testimony.style-blurb, short="Testimony of John Bell"]
== The Testimony of John Bell, to the memory of our worthy Friend, James Dickinson, deceased.

Reader, you are, with this,
presented with a brief account of the diligent labours and hard travels,
of that faithful servant and eminent minister of the gospel of Christ, James Dickinson;
to whose faithfulness to the Truth, manifested in a humble,
self-denying life and circumspect, godly conduct,
I could not but give this brief testimony;
for it was this which greatly recommended that ministry in which he
zealously laboured for the promotion of piety and virtue,
both at home and abroad;
so that it often proved effectual to reach the witness of God
in the consciences of those to whom he ministered.
It may be truly said of him,
that he went not about to publish the gospel of life and
salvation with enticing words which man`'s wisdom teaches,
but in the power and demonstration of the Spirit;
for he was not a minister of the letter only, but of the Spirit:
it was by being obedient to the powerful workings thereof in himself,
and by waiting diligently for the movings and openings of it,
that he became well qualified for that service.

His testimony was living and powerful,
and often very terrible to the workers of iniquity,
yet very edifying and comfortable to the well-minded,
and encouraging to them to wait for the help of the Holy Spirit,
whereby they might be made able to persevere in the way of life and salvation;
which way is revealed and made manifest by the light of the Son of God,
which in some degree shines in the hearts of all mankind,
and is the unerring Guide to all such who believe in it,
and are obedient to its discoveries, to bring them to the strait gate,
and into the narrow way which leads to eternal happiness.
By his powerful and lively testimonies,
the weak and doubtful were often encouraged to depend upon that powerful Arm,
whereby they had been gathered out of the many evils which are in the world;
and the feeble-minded confirmed in the belief of the Truth,
and their faith strengthened in Jesus Christ the way to the Father.
For he was often concerned in the openings of Truth,
to speak to the various states and conditions of
the people to whom he was called to minister,
having through the mercy of God the word to preach,
and wisdom given him to divide it aright;
and many yet living who have sat under his
testimonies with great comfort and satisfaction,
can witness that he did not "`handle the word of God deceitfully,`"
but was "`a workman that needed not to be ashamed.`"

He was an able minister of the new covenant, a zealous promoter of the cause of Truth,
and laboured faithfully in that good work whereunto he was called,
in that ability which God gave.
He travelled much in that service through many difficulties and hardships,
and at times in great jeopardy; but as his dependence was upon God,
whom he faithfully served and obeyed, he was preserved through all those difficulties,
and enabled to perform his service, and cheerfully to undergo the hardships he met with;
for the Lord had blessed him with a good constitution and bodily strength,
so that he was well qualified both with spiritual and temporal ability,
for that service whereunto he was called and appointed,
as plainly appears by his journal.
For, as has been already said, he laboured faithfully where he came,
in word and doctrine; and many were turned from darkness to light,
and from the power of satan to God by his ministry, and the flock of Christ edified,
comforted, and encouraged in a faithful perseverance.

And although he travelled much, and often hard, as plainly appears by his said journal,
(not being willing to make the gospel chargeable,) yet
when he was drawn forth to visit the churches abroad,
as soon as his service was over, and his spirit eased of the concern which was upon him.,
it appears, he was diligent to return to his outward habitation and business,
that he might not only be a good example to others,
but might also mind his service among Friends at home.
A good example indeed of an able minister and faithful elder of the
church of Christ! worthy to be observed and followed by all,
to whom a dispensation of the same gospel is given to preach;
for wheresoever any are truly qualified and called to the ministry,
there will be a service for them among Friends where they dwell,
in that ministry whereunto they are called;
so that when any are called to visit any of the churches,
there ought still to be a care upon their minds to return,
when they have discharged themselves faithfully of that concern required of them:
for the truly called of God will find,
if they diligently mind the manifestations of
the Holy Spirit which qualifies for service,
and leads the obedient servants of Christ into it,
that there is a service for them to do among Friends,
in those places where they are inhabitants; and the care of the churches there,
according to their several growths, will fall upon them;
and this service ought not to be neglected; for wheresoever that may happen,
such will suffer loss.

Therefore I would tenderly advise, in the love of Christ,
all who are concerned in the work of the ministry,
that they be very careful to mind this their service; and, by that help given of God,
endeavour to follow the example of this faithful and experienced elder: for,
according to his account in the preceding journal,
(to the truth whereof many now living can testify,) when he returned
from his labours and travels abroad in visiting the churches,
he diligently attended the particular meeting to which he belonged,
also was often concerned to visit neighbouring meetings;
and not less careful to frequent meetings for discipline,
that he might be helpful to his brethren in the management of the affairs of Truth;
which nearly united them one to another.

But, by what is above said by way of caution,
I do not intend to discourage any who are rightly concerned; but on the contrary hand,
would recommend the advice of the apostle to Timothy, "`Let the elders that rule well,
be counted worthy of double honour,
especially they who labour in the word and doctrine.`"--1 Tim. 5:17, and not only so,
but I would also beseech Friends,
when it may please God to raise up and qualify any for the work of the ministry,
that they do not slight it, nor despise the instruments who may be so concerned,
how mean soever they may appear in the eyes of men; for it is the Lord`'s work,
who is able to qualify: but be diligently exercised in your minds,
that they may feel the help of your spirits for their strength and encouragement;
for the exercise and concern of the true ministers,
is of more weight to them than some are aware of.

As to this our worthy Friend, he was a man much esteemed in his own country,
and Friends there highly valued him for his work`'s sake and his faithfulness therein;
and his humble deportment, circumspect life and godly conduct,
gained him a good report among his neighbours, and those with whom he conversed.

He also frequently attended the yearly meeting in London; and the still,
retired frame of mind he often sat in, when in that meeting,
has affected the minds of some who have beheld him; and when he spoke to matters,
it was in humility, and very weighty, greatly to the satisfaction of many brethren,
his words being seasoned with grace.
Yet he was not so peculiarly gifted, for the management of the discipline of the church,
as some others in his time, who were not so eminent in the ministry;
whereby the great wisdom of the Almighty is plainly seen;
for he fits and qualifies his faithful servants, by his own power and Holy Spirit,
for that work and service in the church, to which he sees fit to appoint them;
as the apostle said; "`Now there are diversities of gifts, but the same Spirit;
and there are differences of administrations, but the same Lord;
and there are diversities of operations,
but it is the same God which works all in all.`"--1 Cor. 12:4-6. And the apostle,
when he speaks of Christ`'s ascending up on high, when he led captivity captive,
and gave gifts unto men, goes on, and further says, "`And he gave some apostles,
and some prophets, and some evangelists, and some pastors and teachers,
for the perfecting of the saints, for the work of the ministry,
for the edifying of the body of Christ,`"--Eph. 4:11-12. And as
the church comes to be restored into its primitive purity,
the same Lord is able, in our day, to quality his faithful servants,
and give gifts to them for the perfecting the saints,
that the body may edify itself in love.
It was for the work of the ministry that this our worthy Friend was peculiarly gifted,
in which he laboured faithfully many years, and was an example of humility and meekness;
which with his pious life and godly conduct,
greatly adorned the doctrine he had given him to preach;
for he walked in the "`just man`'s path,`" which "`is as the shining light,
that shines more and more, unto the perfect day;`" Prov. 4:18;
and his '`zeal for the cause of Truth continued,
while strength of body was given him to perform his service.

I shall now recommend to Friends in general,
the serious perusal of the foregoing journal; wherein is set forth the protection,
and many preservations of the author, by that mighty Hand and Power on which he depended;
that every one may be stirred up to rely on the same
divine Arm which preserved him during a long pilgrimage,
through many exercises and difficulties; that by the help of the Holy Spirit,
many may be enabled to follow this faithful man`'s good example in humility, piety,
virtue, and faithfulness to the Truth we profess.
And now that it has pleased the Great Creator of all things to remove him from us,
and to take him to himself, he having ceased from his labours, his works follow him;
and I doubt not, but through Jesus Christ our Mediator,
he has obtained an entrance into that everlasting rest which remains for the righteous.

And his memory lives with the faithful who knew him: for, as the psalmist says,
"`The righteous shall be in everlasting remembrance;`"--Ps. 112:6: and,
as Daniel the prophet says,
"`They that be wise shall shine as the brightness of the firmament;
and they that turn many to righteousness,
as the stars forever and ever.`"--Dan. 12:3. May we, by following his steps,
attain the like reward; and with him, among saints and angels,
and the spirits of just men made perfect, praise God our Redeemer,
and receive that crown of righteousness,
which is laid up for all those who love the appearance of Jesus Christ our Lord;
unto whom, with the Father, be dominion and glory, thanksgiving and praise,
now and forever.

[quote.scripture]
____
"`Blessed are the dead which die in the Lord, from henceforth: Yes, says the Spirit,
that they may rest from their labours; and their works do follow them.`"--Rev. 14:13.
____

[.signed-section-signature]
John Bell.

[.signed-section-context-close]
Bromley, the 12th of the Ninth month, 1744.
