== To the Reader

The Apostle John was instructed to write, "`Blessed are the dead which die in the Lord,
from henceforth: Yea, saith the Spirit, that they may rest from their labours;
and their works do follow them.`"--Rev. 14:13.
And it is no ways strange that he should be instructed so to write,
considering what is elsewhere said,
that "`Precious in the sight of the Lord is the death of his saints,`"--Ps. 116:15;
and that it is the end of all their labours,
(and a blessed end it is indeed,) to which the crown is promised;
as was said to one of the churches, "`Be thou faithful unto death,
and I will give thee a crown of life.`"--Rev. 2:10.
This is to them an end of all their labours,
jeopardies, hardships, and sufferings;
and they are landed safe in that much to be desired port,
"`where the wicked cease from troubling, and the weary are at rest.`"
But then, if their labours are so acceptable to the Lord, and their works follow them,
(for the reward is to be according to them, Matt. 16:27,
in that glorious kingdom they are entered into,) how
precious ought they to be in the sight of his servants!
Even the remembrance of them ought not to be lost, but the fragments to be gathered up,
that they may be transmitted to posterity for their imitation and encouragement,
and this not in any wise for the exalting of man,
but that the Power whereby they have been raised up, preserved, and carried through,
may be exalted.

For this, even that Power, was their wisdom and their strength,
and blessed are all they who put their trust in it;
that according to the example of the psalmist,
one generation may praise his works to another,
and declare his mighty acts,--Ps. 145:4,
even those mighty acts which the Lord hath wrought through his servants,
whom he hath been pleased to raise up from a low estate, and to set among princes,
even the princes of his people, and to declare the might of his arm.
He is pleased to carry on his own work by mean instruments in the world`'s account,
that no flesh might glory in his presence; as the apostle writes,
"`For ye see your calling, brethren; how that not many wise men after the flesh,
not many mighty, not many noble, are called:
but God hath chosen the foolish things of the world to confound the wise;
and God hath chosen the weak things of the world to confound the things which are mighty;
and base things of the world, and things which are despised, hath God chosen.`" 1 Cor. 1:26-27.
And this hath been wonderfully made appear in this generation,
and the generation preceding;
wherein God hath been pleased to carry on his glorious work of reformation,
in causing the Gospel to be preached again, after a long night of darkness,
by mean and illiterate instruments in the world`'s account; by whom they have been,
and still are, accounted as fools:
and yet how mightily it hath pleased God to prosper his work in their hands,
to the gathering many souls near to himself, and into unity with his blessed Spirit,
through their ministry.

Of this number was our friend James Dickinson, the author of the ensuing journal,
a man indefatigable in his labours and services for the edification of the church,
and the good of souls;
whose ministry was not in the enticing words which man`'s wisdom teacheth,
but in the demonstration of the Spirit and of power,
and in that wisdom which the Holy Ghost teacheth;
and was effectual to the convincing and gathering many,
and settling them upon the rock Christ Jesus, and under his teaching,
who is the foundation of all the righteous generations;
in whom all such who believe shall not be ashamed,
nor shall be any "`more strangers and foreigners, but fellow citizens with the saints,
and of the household of God,`" as saith the apostle, Eph. 2:19.

And reader,
if thou peruse the following account of the
services and labour of love of this man of God,
with an unprejudiced mind,
and with a desire to be informed and helped forward in thy spiritual journey, thou wilt,
no doubt, reap advantage by it, and be encouraged to press forward;
and it will be to thee a savour of life unto life; that is,
the savour of life that will attend thee in the reading of it,
if thou read it with a single eye, will tend to promote the same life in thy soul,
and thou wilt desire, according to thy measure,
to be found walking in faithfulness towards God:
for this is that which can only recommend to him;
and thus will the end of the labour of his faithful servants be answered.

And if thou find any thing which seems not so clearly and fully set forth,
or that he is short in his account concerning his travels in some places,
thou needst not wonder at it, considering how much he was employed in public service,
and almost continually travelling to and fro in the work of the ministry;
but it is rather to be admired that he was capable of transmitting so much,
and that so well as he has done; and not only so,
but also as he was a man who had not the advantage of a liberal or learned education,
but like the disciples of his Lord formerly,
(see Acts 4:13) was ignorant and unlearned in that literature;
though he was wise unto that which is good, and simple concerning evil,
and was able with the blessed apostle,
"`to speak wisdom among them that were perfect,`"--1 Cor. 2:6;
and to declare his experience in the things of God,
and the mysteries of true godliness and saving religion: and therefore it is hoped,
that inaccuracies in style and manner of expression, or otherwise,
will be overlooked and excused by the candid and ingenuous reader.

As to the account of his acceptance among Friends where he lived,
and the service he was of in the meeting he belonged to,
we refer to the testimony concerning him from
the monthly meeting of which he was a member,
herewith published;
and shall conclude this preface with this short
exhortation to every particular (but more especially to
the youth,) who may read the ensuing treatise:
Wouldst thou be a vessel of honour in the house of God,
and of service in thy day and generation,
(as this our worthy friend was,) according to
thy degree and station in the Church of Christ?
Thou must then keep under the government of the grace or Spirit of God,
which made him what he was, and learn to trust in it: for "`Abraham believed God,
and it was accounted to him for righteousness.`"--Gal. 3:6;
and so it will be to all his children after the promise: and seek not thine own honour,
for "`how can ye believe who receive honour one of another,
and seek not the honour that cometh from God only,`" saith Christ our Lord and Pattern, John 5:44.
And if thou keepest under the government of the Spirit or grace of God,
to the manifestation of his light in thy own heart, (which are all one thing,
under different names,
according to the diversities of the operations of God`'s
universal gift dispensed for the redemption of mankind,
and have all the same or the like properties and effects ascribed to
each of them,) thou wilt receive power to become a child of God,
and inherit the promises.
Concerning which terms of grace, spirit and light,
for the sake of such who may be strangers to this doctrine,
a few Scripture testimonies are subjoined, viz:

[.numbered-group]
====

[.numbered]
1st, Under the term grace:
"`By grace are ye saved through faith.`"--Eph. 2:8. God`'s "`grace
is sufficient for thee.--2 Cor. 12:9. It is that which "`teacheth
to deny ungodliness and worldly lusts,
and to live soberly, righteously, and godly.`"--Titus 2:12.

[.numbered]
2ndly, Under the term Spirit: "`When the Spirit of Truth is come,
he will guide you into all truth.`" John 16:13.
"`The things of God knoweth no man, but the Spirit of God.`" 1 Cor. 2:12.
"`But God hath revealed them to us by his Spirit.`" 1 Cor. 2:10.
"`Grieve not the Holy Spirit of God,
whereby ye are sealed unto the day of redemption.`" Eph. 4:30.
"`As many as are led by the Spirit of God,
they are the sons of God.`"--Rom. 8:14. "`Now if
any man have not the Spirit of Christ,
he is none of his.`"
Rom. 8:9;
for it is through the Spirit the deeds of the body (which are our lusts) are mortified. Rom. 8:13.

[.numbered]
3rdly, Under the term Light:
Christ is "`the true Light which lighteth every man that Cometh into
the world,`" (John 1:9) as he declares of himself,
"`I am the light of the world; he that followeth me shall not walk in darkness,
but shall have the light of life.`"--John 8:12. And thus is
fulfilled what the prophet foretold concerning him,
that "`God gave him (his Son) for a covenant of the people,
for a light of the Gentiles.`"--Isa. 42:6. And again he says,
"`I will also give thee for a light to the Gentiles,
that thou mayest be my salvation unto the end of the earth,`"--Isa. 49:6;
and also by Zacharias, "`to give light to them that sit in darkness,
and in the shadow of death,
to guide our feet into the way of peace.`"--Luke 1:79.
And this is what the Apostle John gives testimony to,
that it was come; "`because,`" saith he, "`the darkness is past,
and the true light now shineth.`"
1 John 2:8; and exhorts the believers to walk in it, chap.
1:7; and what the Apostle Paul bears record of, when he says,
"`But all things that are reproved, or are (discovered,
as in the margin,) are made manifest by the light,`" Eph. 5:13.;
and this is that light with which the heavenly city, the new Jerusalem, is enlightened,
and therefore "`needs not the light of the sun or of the moon,
but the glory of God doth lighten it, and the Lamb is the light thereof;
and the nations of them which are saved, shall walk in the light of it.`" Rev. 21:23-24.
And it is to this gift, which is the saving health of all nations,
the apostle recommends the believers in his time, under the term grace,
and to which all who have known the sufficiency of it, do direct all: "`And now,
brethren, I commend you to God, and to the word of his grace,
which is able to build you up,
and to give you an inheritance among all them which are sanctified.`"--Acts 20:32.

====

To God only wise, who is glorified in his saints, and preserves, through all,
to his heavenly kingdom such who put their trust in him, be dominion and thanks,
now and forevermore.

Amen.
