== Chapter I.

[.chapter-synopsis]
* His birth
* Care and Faithfulness of His Parents
* His Transgression and Conviction
* Religious Exercises and First Appearance in the Ministry
* Visits to a Presbyterian and Baptist Meeting, etc.
* Travels in Various parts of England and Wales, also in Scotland, Ireland and Holland
* His First Visit to America
* Remarkable  Deliverance on the Voyage
* Travels and Gospel Labours in America

I was born at a place called Lowmoor-house,
in the parish of Dean and county of Cumberland, in the year 1659.
My parents`' names were Matthew and Jane Dickinson, who being convinced of the Truth,
educated me in the way thereof; and the Lord, by his power,
did reach unto me when very young, and often broke my heart into true tenderness,
so that many times I had a secret delight to be
inwardly retired to feel the virtue of it;
which was cause of true gladness to my parents,
whose delight was in the enjoyment of the Lord`'s presence.
They were good examples to their children, educating them in the way of righteousness:
often exhorting us with tears to fear the Lord,
sincerely desiring that their children might be his.
My testimony for them is they discharged themselves to their children.

When I was about seven years of age,
it pleased the Lord to remove my dear mother from the cares and troubles of this life.
My father retained his integrity and zeal for God and his Truth,
and his care still increased for his children`'s good,
that they might grow up in the Truth; often admonishing us to fear the Lord,
and to mind his light and grace that secretly reproved us for
the wildness and the outgoings of our minds into vanity:
so that I may say they are clear of us, and am satisfied they are entered into rest,
and their works follow them.

My father died when I was ten years old; and I not taking the counsel of the wise man,
viz. to take the counsel of my father,
which was to mind the light or measure of grace given unto me,
my mind was drawn out after the vain plays, customs, fashions,
and will-worships of the world; in which state I continued some time.
Yet the Lord by his power did many times reach my heart,
and by the Spirit of his dear Son, the Lord Jesus Christ,
reproved me for my vain conversation;
many times calling me to return unto him from whom I had gone astray; whose power,
in some measure, I had felt before to tender my heart.
But not minding to turn at the reproofs of wisdom,
I went on in rebellion against his blessed Spirit,
and ran as with a multitude to do evil, into wildness and vanity;
until the Lord in his mercy did visit my soul by his righteous judgments,
and thereby turned my mirth into mourning, and joy into heaviness;
and deep sorrow was my portion.
Being warned to repent and turn to the Lord, a godly sorrow was begun,
which I experienced to lead to true repentance.
Then my familiars became my enemies, and I was a taunt and a bye-word to them: yet still,
as I loved the Lord in the way of his judgments,
and waited upon him to know the way of them, I found the Lord to give victory,
and saw my greatest enemies were those of my own house, and the war begun there.
And as I was careful to keep in the light, I came to see the kingdom rent from Saul,
and given to David;
though there was a long war between the house of Saul and the house of David:
but as I kept my eye unto the Lord,
I came to see the house of Saul to grow weaker and weaker,
and the house of David stronger and stronger.

Yet many were the days of mourning and nights of sorrow my soul went under;
that I may say, it was the day of Jacob`'s trouble and of Joseph`'s affliction:
many times I cried unto the Lord, '`O that I had a cave in the ground,
that I might mourn out my days,
that in the end I might find peace with thee!`'
And in those deep afflictions and exercises,
the Lord was very near, and often mixed mercy with judgment;
so that my soul began to delight to wait upon him in the way of his judgment,
seeing it was by the spirit of judgment and burning,
that the filth of the daughter of Zion must be done away.
As I kept here, I felt the love of God to increase in my soul, which deeply affected me;
and a hunger was increased in my heart after the enjoyment of the Lord`'s power,
and the operation of it, whether it was in mercy or judgment;
so I knew my faith to be increased in the sufficiency of the power of God.
Then I saw it was good for me that I was afflicted;
for "`before I was afflicted I went astray;`"
I found (as David said) his rod and his staff comforted me;
and the Lord did often overshadow me with his love,
and a sight of glorious things I had at that time.

I also had a vision, in which I beheld a sheep feeding in a very green pasture,
by a pleasant river-side; and a wicked man, that envied the sheep,
came and forced it into the river, and the sheep made for the other side;
but a bridge being over the river, the man went over it and drove the sheep in again,
and so resolved to drown it.
When the sheep was almost lost, I saw a good man, that was the owner of the sheep,
who caught hold and saved it and brought it into the pasture again;
after which I saw the two men striving upon the bridge;
and he who saved the sheep prevailed, and smote the other,
and threw him into the river in which he would
have drowned the sheep and it took him away.

After this, great was my exercise,
tossing and struggling with the power of darkness being unskilful,
and not grown in strength to resist the evil one, he gained ground upon me,
and would have filled me with doubts and fears,
so that I was ready to conclude I should never get through; but, with David,
was like to say, "`I shall now perish one day by the hand of Saul.`"
And when I had almost lost the hope of deliverance,
then the Lord appeared by his mighty power, and rebuked the enemy,
and delivered my soul from him that was too strong for me;
he drew me out of the troubled waters, and brought my mind into true stillness,
and to the proper place of right waiting upon him,
where I found my strength to be renewed;
and the overshadowing of his power I often felt to my great comfort,
so that I was made to admire his goodness.

In the year 1678,
the Lord moved upon me by his Spirit to bear a testimony to his name and Truth.
Great then was my exercise: seeing the work to be very weighty,
and looking out at my own weakness,
made me unwilling to give up to answer the Lord`'s requirings; but the Lord,
in his great love, filled my soul with the emanations of his power,
which strengthened and encouraged me,
that I was made willing to give up in obedience unto his divine will.
Then in great dread and fear I stood up, and bore a public testimony in our own meeting,
warning Friends to be more inward and faithful to the
manifestations of the light and grace of God in their souls.
And after I had answered the requirings of the Lord,
I found great peace flowing in my soul, which so prevailed upon my spirit,
that I was bowed down under the sense of the Lord`'s goodness;
and the weight of the exercise which I had felt upon me was removed.

One morning, as I was meditating on the great love and mercy of God unto my soul,
the word of the Lord came unto me saying.
Be bold and courageous for my name`'s sake, and I will raise thee up;
and shortly after he moved upon me to go to Talentire, to the Presbyterians`' meeting.
I was under a continual exercise for several days and nights,
so that I could scarcely either eat or sleep;
and the word of the Lord was as a fire in my bones,
that I had no peace till I had given up to it: so I went, and the Lord was with me,
and showed me what I had to do.
When I came into the meeting at Talentire, I stood amongst them in great fear and dread;
and immediately the people began to say, I was a Quaker,
and was come to disturb the meeting: some cried, '`put him forth,`' others,
'`let him alone;`' so they were divided,
as the multitude amongst whom Paul was concerned to preach the gospel.
Some pulled to have me out, and others seemed to stop them.
But they put me out, and shut the door, and many people followed me.
I stood up amongst them at the window, and delivered the message I had to them,
which was,
'`This is the day of the visitation and the revelation
of the power and Spirit of Christ in your hearts;
therefore resist not the day of the visitation and revelation of God`'s Spirit;
for if you do, it will rise up in judgment against you,
when you will not be able to resist.`'
After I had thus spoken, they ran to me and threw me down,
dragged my head against the stones, and put me out of the gate.
Then I spoke to them; but two of them came and haled me down the street.
And finding myself clear, I said, '`Your blood be upon your own heads,
for I am clear of it.`'
So I came away in great peace of mind,
being sensible of the overshadowing of the love of God,
and was filled with praises unto his most holy name.

And soon after,
the Lord by his Spirit moved upon me to go to the Baptists`' meeting at Broughton;
unto which I gave up; and the Lord was with me to my consolation.
So I went, in obedience to the will of the Lord, into their meeting,
and staid a considerable time, until the preacher, who was a stranger, made a stop:
then I spoke, and desired liberty to clear myself among them;
after which I directed the people to the light of Christ Jesus.
John Palmer the elder bid me begone out of his house,
and commanded his son to put me forth;
so he took me by the shoulders and pushed me out at the door,
and kept me there till the meeting was ended.
Then I went in again,
and preached unto them the light of Christ Jesus that shined in their hearts,
in order to give them the knowledge of the glory of God.
Thus, although I was thrust out of doors,
yet the Lord made way for me to clear myself of the weight that was upon me,
blessed be his name forever.

But great was the confusion that soon appeared, many of them speaking all at once;
some asking, What beast was that which was come amongst them?
Others answered.
It was none, but a man or a boy.
But the Lord was with me in my testimony,
and by the effusion of his power gave me dominion over the unclean spirits;
and the witness of God in the hearts of several, was reached,
who soon after came out from amongst them, and received the Truth in the love of it,
viz., John Ribton, who came to be a minister of the gospel, and several others.
And when I was clear I came away, and witnessed that saying to be fulfilled.
Ps. 119:165, "`Great peace have they which love thy law, and nothing shall offend them.`"

After some time, the Lord engaged me to visit Friends in this county;
and as I gave up in obedience thereto,
I witnessed the renewings of divine love in my heart,
which was cause of joy and true gladness to my soul.
In my return home, a concern came upon me to go and speak to George Larkham,
a Presbyterian preacher, at Talentire; which brought a fresh exercise upon my mind,
because I was unwilling to answer what the Lord required of me,
insomuch that my natural strength was almost taken from me:
then I was made willing to do whatsoever the Lord required of me.
So I went, in the fear of the Lord, into George Larkham`'s house.
As soon as he saw me he was in great fury and rage,
and asked me what business I had there?
I told him my business was to clear my conscience in the sight of God,
which I desired he would suffer me to do;--but he in great
rage ran into an upper room and ordered me to be put out,
for I was a Quaker: his wife being also in a great passion, said,
there was a great fault of the magistrates,
in not putting such fellows as I in the stocks;
which showed the bitterness of her spirit,
and that she only wanted power to follow the example,
and imitate the barbarity of her brethren in New England.
Then George Larkham came down in great fury, and asked why they had not put me forth?
I desired him, if he was a Christian, to show his moderation as a Christian.
Then he charged me with saying that he was no Christian;
which I told him was false:--he said,
some of my persuasion had said it;--I bid him charge them with it, and not me falsely.
Then he took me by the shoulders and thrust me out of the house,
as his followers had done before:
and as I was going out I spoke to him what I had upon my mind.
So I came away in much peace, feeling the Lord to overshadow me with his living presence,
which filled my heart with praises to his great name.

In the year 1680, I felt the Lord, by his power,
to draw me forth to visit Friends in Westmoreland, the dales of Yorkshire,
the bishoprick of Durham and Northumberland;
in which journey the Lord was merciful unto me,
in preserving and giving me my life for a prey.
Great was the zeal that was raised in me for the Truth,
and against any thing that was contrary to and opposed it.
This was a time when Friends were under great exercises and deep sufferings,
by reason of wicked and ungodly men; for many were imprisoned, fined,
and had their goods taken from them,
for no other reason but performing their religious duties to Almighty God,
in worshipping him in spirit and in truth:
although no informers came to any of the meetings appointed by me,
in all my journey through Westmoreland, etc.,
which bowed my mind in true thankfulness unto the God of heaven and earth,
for his merciful preservation and divine protection.

In the year 1682, a concern was upon me from the Lord,
to go into Ireland in the service of the Truth, under which I laboured for some time.
Thomas Wilson, a young man from Coldbeck, was at our week-day meeting,
as he was going to visit Friends in Ireland:
and although I did not acquaint him with what was upon my mind, yet after he was gone,
my exercise increased upon me to such a degree,
that I freely gave up unto the manifestations of God`'s will revealed to me.
Then I acquainted my brethren therewith, and they had unity with me therein,
believing the Lord had called me thereunto.
So I took leave of them in much tenderness in the love of God,
took shipping at Workington for Ireland, and arrived safe at Dublin.

The next day I went to their meeting;
and the Lord by his ancient goodness did eminently break in amongst us,
and refreshed our souls with his divine love,
which brought me under a renewed obligation to celebrate his great name,
who had preserved me both by sea and land.
After the meeting I went into the country,
and visited Friends`' meetings until I came into the county of Wexford,
where I met with Thomas Wilson; and our concerns being one way,
we travelled together through the provinces of Leinster and Munster, in great humility,
godly fear and true brotherly love; our hearts being often tendered in meetings,
and the hearts of Friends also, in most places where we came.
So being clear of those parts, my companion staid at Waterford, and I went north,
and had several meetings amongst people that professed not with us;
and several were convinced.

Now finding myself clear of the north, I returned to Dublin,
and had some service in that city; so took shipping for Whitehaven.
In our voyage, near the Isle of Man, we had a great storm and were in danger;
but through the good providence of God we got to land in Wales,
where I had some service for the Truth; after which, we proceeded on our voyage,
and arrived safe at Whitehaven; so went home,
being truly thankful unto the Lord for his manifold preservations both by sea and land.

In the year 1683, I felt drawings in my mind to visit Friends in Scotland;
and being resigned to answer what I believed was required of me,
I took my journey on foot, not having any companion;
yet the love of God was such in my heart, that I freely gave up to follow him.
When I was in the Border,
a young man belonging to that meeting had a concern to go along with me,
whose company was both serviceable and acceptable;
our unity was sweet and pleasant in the Lord.
We travelled on foot through the south,
and the Lord was with us and enabled us to perform our services.
Then we passed into the north to Aberdeen, etc.,
where we met with our friends George Rook and Andrew Taylor.
We were at several meetings together,
and were sweetly comforted in the Lord and one another.
We had a meeting on board a ship that was bound for Jersey in America,
there being several Friends on board that were passengers.
After the meeting, we took leave of them in the love of God;
so travelled through the north,
and had many refreshing seasons in the enjoyment of God`'s love;
several hearts were reached and some convinced.
When we were clear, we returned into the west and visited Friends there;
so returned into England as with sheaves in our bosoms,
which occasioned praises to spring in our hearts to the Lord.

Some time after, I was drawn forth to visit Friends in the north of England,
and proceeding into Westmoreland; at Kendal I met with my dear companion, Thomas Wilson,
who was my fellow-labourer in the work of the gospel of our Lord Jesus Christ.
We had a meeting there, and it being a time of great persecution,
many Friends suffered deeply by wicked and unreasonable men;
but the Lord supported us in the time of exercises.
A little after we were gone into the meeting, the officers came and were very rude:
Thomas Wilson stood up and preached the gospel in the authority of the power of God,
which mightily affected the hearts of Friends:
then one of the officers came and pulled him out of the meeting, and kept him there:
after which I was engaged in the love of God,
and stood up and bore a testimony to his name and Truth.
Then the officers said, '`There is another preaching;
they will never be quiet so long as any are left in the house.`'
So they took me forth also, and kept us a little time,
but suffered us to go into the meeting again; and we sat down and waited upon the Lord.
Some time after, I was engaged in prayer: they came rushing in to pull me away again,
but the power of the Lord was over all, which so chained down that persecuting spirit,
that they had not power to break up our meeting; but were frustrated,
and the name of our God exalted, and set over the opposers; many,
of their hearts were reached by his divine power: thus we saw that saying fulfilled,
"`When a man`'s ways please the Lord,
he maketh even his enemies to be at peace with him.`"--Prov. 16:7.
Then I parted with my companion and went into Lancashire and the edge of Yorkshire,
where several were convinced at that time.
Finding myself clear, I returned home and followed my trade,
which was that of a felt-monger, and was diligent in attending our own meetings,
in which I had peace and inward satisfaction of soul.

In the year 1684, I with my companion Thomas Wilson,
travelled through Lancashire and Cheshire into Wales.
Friends were still under deep exercises by reason of the persecuting
spirit which was risen up against the church of God,
insomuch that Friends were often imprisoned, fined, and had their goods taken from them.
But we were drawn forth by the love of God,
who sets bounds to the waters and rebukes the seas;
causeth the horn of the wicked to be broken,
and restraineth the remainder of the wrath of man,
when he hath suffered the rod of the wicked to be laid
upon the back of the righteous for a season,
for a trial of their faith, that it may appear much more precious than that of gold;
that by it, they may live through all, and follow the Lamb through many tribulations,
and know their garments washed in his precious blood.
Blessed be the Lord, we were made witnesses of his divine power in our travels,
both inwardly and outwardly.

We entered into North Wales in the depth of winter;
and all things were made pleasant unto us in the love of God,
which we were measurably made partakers of.
At the first meeting we had in Wales the Lord did eminently appear amongst us,
and filled our hearts with praises unto his holy name.
So we travelled through North Wales, and had good service for the Truth.
Robert Vahan was there convinced of the Truth, and became a very serviceable man,
being afterwards called to the work of the ministry.
Then we went into South Wales to Haverfordwest,
and had good service there among the people.
In all this way, no informers came to any of our meetings,
until we came to Redstone in Pembrokeshire; there we had a meeting,
unto which came two informers.
My companion was preaching the word of the Lord to the people when they came in:
one of them came to take him out of the meeting, but the Lord restrained him:
so he went on, and the Lord was effectually with him by his irresistible power;
and in much plainness and tenderness he set the testimony of Truth over their heads.
After he had cleared himself he sat down: then the informer swore a great oath, and said,
"`There should not another word be spoken there:`" but finding
my heart engaged in the love of God to pray to Him,
and implore his divine assistance, the informer came to pull me away, but he could not;
for the Lord by his power restrained him,
and set his Truth over the heads of the opposers.
Friends`' spirits were raised into dominion over the adversary and his instruments,
the meeting ended in praising and giving of thanks unto the Lord,
and we came away in sweet peace.
We may say, the Lord fulfilled the promise made to Jerusalem, unto us,
"`That he would be unto her a wall of fire round about,
and the glory in the midst of her;`"--Zech. 2:5.
for the overshadowing of his love was with us,
and we had many precious meetings in those parts.

Then we went to Swansea and had service there;
persuading the people to be reconciled to God and one to another.
So came into North Wales, where I parted with my companion; he returned home;
but I having a concern upon me to visit Friends in Ireland,
went through the north into the Isle of Anglesea,
and took shipping at Holyhead for Dublin.
Having a fair wind, we had a prosperous voyage, until we got Over the bar of Dublin;
then a great storm arose, the vessel struck ground,
and we were in danger of being wrecked; but the Lord ordered it otherwise.
So I got safe to Dublin,
which filled my heart with thankfulness to the Almighty for so wonderfully preserving us.
John Burnyeat landed in the north of Ireland, through great danger, at the same time;
it was such a storm, that few vessels got to Ireland for two weeks after.
Then in obedience to the will of God, I went into Leinster and visited Friends,
where I met with Thomas Trafford,^
footnote:[Thomas Trafford resided in Ireland.
According to the testimony of Friends of the county of Wicklow,
"`he was convinced of the Truth about the year 1670,
and soon after bore a faithful testimony for the
Lord against that grand oppression of tithes;
and because, for conscience`' sake, he could not pay the same,
he suffered imprisonment for two years.
Soon after he came out of prison, the Lord committed to him a dispensation of the gospel,
which he preached freely and faithfully in this nation, through which he often travelled,
also several times in some parts of England, etc.
Several were convinced by his ministry,
and Friends were often comforted by the sweetness of
that life and power which attended it.
He was also zealously concerned in discipline,
being endued with a sound and clear understanding,
very tender and encouraging to the good, and zealous against the appearance of evil.
Towards the latter part of his life he suffered great bodily affliction;
yet he bore it with patience, was preserved in a sweet frame of spirit,
and continued very serviceable in his meeting unto his latter end.
He died in the year 1703.`"
{footnote-paragraph-split}
Thomas Trafford appears to have borne a large share of the
concern that rested on many Friends of Ireland in his day,
that themselves and their fellow-professors might be preserved from
that "`spirit which leads into the lawful things of the world,
beyond the bounds of Truth.`"
(See a weighty Epistle on that subject, with a Preface and Postscript thereto,
in Rutty`'s _History of Friends in Ireland._)]
who travelled through Munster with me.
I had a general warning to Friends,
to be careful that they might have a habitation and settlement in the power of God;
for a time of trial would come upon them, that would try all their foundations;
and none would be able to stand, nor be safe,
but those that should be settled upon the Rock, Christ Jesus,
and gathered under his peaceable government; those would know a dwelling safely,
and a being quiet from the fear of evil.^
footnote:[That the fulfilment of this prediction soon followed,
is a well-known historical fact:
the following summary account of it furnishes occasion for contemplating,
with reverent admiration, the sufficiency of that divine Arm,
whereby Friends who kept faithful to their testimony against wars and fightings,
were preserved; and enabled,
under peculiarly adverse circumstances to continue in the performance of
their civil and religious duties.
{footnote-paragraph-split}
"`The latter end of this year (1688) a war broke forth in this nation,
threatening a general over throw of all the English and Protestants;
and in that frightful time, many of these left their dwellings, stocks and flocks,
and fled, some to England and some to arms.
But Friends generally kept their places, and kept up their meetings,
and trusted the Lord with their lives and substance,
that rules all things in heaven and earth,
and bounds the sea and the raging waves thereof;
though under great perils of divers sorts, by reason of multitudes of wicked, unmerciful,
blood-thirsty men, banded together.
And Friends in some places, became great succourers to some of the distressed English,
that had their houses burnt; and were themselves driven out of their places,
being stript of their substance: and a remarkable thing, never to be forgotten, was,
that they that were in government then, seemed to favour us,
and endeavour to preserve Friends.
But notwithstanding all endeavours used, Friends sustained great losses,
and went through many perils, by the outrageous rabble and plunderers of the country,
besides the hardships of the army: so that many lost most of their visible substance,
and some were stript naked,
and their houses and dwellings were set on fire over their heads,
and burnt to the ground; and their lives were in such danger,
that it seemed almost impossible that they should be preserved; yet,
in the midst of such lamentable exercises,
the Lord`'s eminent hand of deliverance wonderfully appeared to their
great admiration and comfort.`"--Rutty`'s _History of Friends in Ireland._
{footnote-paragraph-split}
It is also well known,
that the safety of conforming to the peaceable spirit of the Gospel,
was in like manner manifested in the case of Friends during the Irish Rebellion,
in the year 1798.]
And as the Lord gave the word, he also gave power and strength to publish it.
It seized upon my spirit when I was in that nation before,
that a day of trial would be brought upon the inhabitants thereof;
I beheld as if they were encompassed with weapons of war.
Having cleared myself, I returned to Dublin, and took shipping for Whitehaven,
where I landed safely, and came home as with sheaves in my bosom;
feeling the evidence of God`'s Spirit speaking peace to me,
which my soul desired more than all.

In the year 1686,
I was moved of the Lord to travel into the west and south parts of England;
and as I was drawn by his Holy Spirit, I was made willing to follow him,
in which I found true peace; and as my eye was kept single,
every day waiting for the motion of the word of life,
I found the Lord to fit and qualify me for every day`'s service,
and endue with power from on high.
So I took my journey through several counties: and when I came to Bristol,
I found Friends were under great sufferings; being kept out of their meeting-house,
the meeting was held in the yard: it consisted mostly of women and children,
many Friends being then in prison;
yet the Lord was graciously pleased to own us with the over-shadowings of his love,
whereby we were encouraged to trust in Him alone,
who is able to preserve his people in the midst of afflictions,
and work their deliverance at his own pleasure.

From Bristol I went into Cornwall,
and had several meetings in places and towns where none had been before,
and found great openness among the people.
At Newlyn and Mousehole they threatened to stone me; but the Lord restrained them,
and enabled me to preach the way of life and salvation in the authority and power of God,
by which many hearts were reached, and a love raised in the people.
I came away in peace, and returned into Devonshire,
where I had a meeting in the street at a town called Kirton:
there were many hundreds of people, some of whom were very sober and attentive;
but others behaved very rudely and cast stones at me,
which was occasioned by the instigation of a priest,
who advised them to stone me out of town,
(as I was told afterwards,) but the Lord preserved me from harm,
and gave me courage and boldness to proclaim the everlasting Gospel amongst them;
his power was richly made manifest, and many hearts were reached thereby;
divers were convinced of the Truth, and a meeting was afterwards settled in that town.

The next day I had a meeting at a place not far distant, where were many sober people;
but a constable came and took me, and carried me before one Justice Tuckfield, who said,
He was informed that I had kept a conventicle, contrary to law.--I asked,
Who informed him?--He replied, I suppose you cannot deny it.--I told him.
The law did not enjoin any man to be his own
accuser.--Then in a very mild manner he said,
The constable informed him;--at which the constable was a little confused,
and appeared ashamed to be called an informer by the justice.

After some discourse, the justice spoke kindly to me, and said,
He would show me all the favour he could, and if I had any thing further to speak,
he was willing to hear me.--I replied,
I am glad that I am brought before a magistrate so willing to hear,
and from whom I expect justice;--which accordingly I had.
I spoke what the Lord opened in my heart to him and the rest of the family,
who seemed to be much affected therewith.
Then he gave me my liberty, and prayed that God might go along with me wheresoever I went.
Thus I came to witness that saying of Christ Jesus our Lord to be fulfilled,
which he spoke to his disciples, viz,
"`Ye shall be brought before governors and kings for my sake,
for a testimony against them and the Gentiles.
But when they deliver you up, take no thought how or what ye shall speak,
for it shall be given you in that same hour what ye shall speak.
For it is not ye that speak,
but the Spirit of your Father which speaketh in you.`"--Matt. 10:18-20. So I may say,
the Lord is the same unto all that he sends forth,
(though as lambs among wolves,) and is mouth and wisdom to his little ones;
goes along with them, and bears them up in all exercises, blessed be his name for ever.

Then I came into Somersetshire and had many blessed meetings:
several were convinced of the Truth: I also went to Bristol.
The storm of persecution being somewhat abated,
Friends who had been in prison were set at liberty: we had very large meetings,
and the Lord, by his infinite love,
was graciously pleased to manifest his power among us,
by which our hearts were tendered before him.
It was a day of God`'s visitation to the inhabitants of that city;
many hearts were reached, several were convinced and received the Truth.
So being clear of the city I went into Wiltshire, where a crafty,
wicked spirit had been at work among Friends, which had separated several from God,
his church and people;
among whom I laboured for the reconciling and bringing of them unto God again:
and the Lord, by his Spirit, enabled me to bear my testimony,
and the hearts of several were reached and helped thereby.
When I had visited Friends in that county,
I appointed a meeting to take my leave of them;
and several of the Separatists were there,
under whose dark spirits my soul had been much oppressed,
and travailed in heaviness and sorrow, which made me cry unto the Lord for deliverance;
and He, that never said unto the seed of Jacob,
"`Seek my face in vain,`" heard and answered; He bore up my spirit in deep afflictions,
and gave me ability to clear myself,
and place judgment upon that rending spirit
which was lifted up above the pure fear of God;
so that I came away in great peace, having my heart filled with praises unto the Lord.

Then I travelled into Dorsetshire, visited Friends in that county, and had good service;
several were convinced of the Truth.
Finding my heart engaged in the love of God to
visit the inhabitants of the Isle of Portland,
in obedience to the Lord`'s requirings I went,
divers Friends from Weymouth accompanying me.
We had a meeting there, to which several of the inhabitants came:
the house not being large enough to contain them, we kept the meeting without doors;
and when I was bowed down in prayer unto the Lord,
a constable came and dragged me from off`" my knees,
with an intent to have cast me into a deep pool of water;
but the people would not suffer him: so he left me,
and I continued supplicating the name of the Lord.
After I arose from prayer,
I was engaged in the love of God to bear a testimony among the people;
when the constable came again, and dragged me from among them, cast me down among stones,
and bruised my body to the shedding of my blood, beat me upon my breast with his fist,
and said, '`If I would not go out of the island,
he would put me in the stocks,`'--and was going to do so, but was hindered by another man.
Then the people gathered about me, and I exhorted them to fear the Lord;
which so enraged the constable, that he took hold of me,
and hit me several blows upon my breast, and dragged me away,
abusing me both with hands and tongue until he had wearied himself:
then he commanded six idle, drunken men, to drag me away,
who took me by the legs and arms, and dragged my head against the stones,
whereby I lost much blood.

Many of the people followed weeping, being troubled to see me so much abused;
for some of my blood was upon all those that laid violent hands upon me.
Then the constable came again, and struck me several times;
thus they continued dragging and beating me until I was scarcely able to stand,
but as I was supported by two Friends.
many concluded I was killed;
but the Lord made it very easy to me by the sweetness of his love,
with which my heart was filled to the inhabitants of that island;
so that I heartily desired the Lord would forgive those that had done me most harm.
Many hearts were reached that day by the power of God.

After the meeting was over, I returned to Weymouth, and had a meeting there that night,
to which several of the inhabitants came, and a blessed heavenly meeting we had;
the Lord`'s power and presence being manifested amongst us,
to the refreshing and comforting of our souls.
From thence I travelled to Ringwood and Southampton, and into the Isle of Wight,
where I had some service among the people; then through Hampshire and Surrey,
visiting Friends`' meetings all along until I came to London,
where I had a comfortable time among Friends.

After I had visited Friends in that city, I went into Kent,
and laboured in the work of the gospel in that ability God gave to me,
in which I found true peace; and many were convinced.
From thence I went into Sussex, and when I had visited Friends there, returned to London.
After some stay there, I travelled into Essex, Suffolk, and Norfolk;
and the Lord largely manifested his love to me,
by which I was enabled to perform the work and service he had called me unto;
so that I found my heart to be daily engaged to follow him in the way of his requirings.
Then I went to Norwich, where Friends had undergone much persecution and imprisonment,
but then had some liberty: many people cam.e to our meetings,
and were very open to receive the testimony of Truth.
I had several comfortable meetings among God`'s suffering children.

After I had travelled through several parts, I returned to London again;
where I met with my brethren,
who came from several parts of this nation to attend the yearly meeting.
The glory of the Lord '`was richly manifested amongst us,
and opened our hearts unto him and one unto another.
Many living testimonies were borne to his great name; so that I may say,
it was like the time of Pentecost, when the disciples of Christ were met,
and filled with the Holy Ghost; for we were met with one accord,
and our hearts were truly tendered in the love of God;
whereby we were enabled to offer unto him the sacrifice of broken hearts,
acceptable and well-pleasing in his sight, who is God, blessed for ever.

Having for some time, had drawings in my mind to visit Friends in Holland,
and some parts adjacent, I took my journey from London along with Peter Fearon,^
footnote:[Peter Fearon resided at Seaton, in Cumberland.
He was educated in the way of the church of
England (so called.) During`' his apprenticeship,
he was convinced of the Truth as professed by Friends; and continuing faithful,
he became concerned to bear a public testimony to the virtue and excellency of it.
He travelled in the service of the Gospel in most parts of England,
as well as in Holland and parts of Germany (as above),
and visited Friends in Scotland and Ireland several times.
He was an able minister, sound in doctrine, convincing to gainsayers,
confirming and edifying to the churches; very serviceable in meetings for discipline,
and zealously concerned therein for promoting good order,
being particularly gifted for that excellent work.
He died in the year 1734, aged 83,
having been a minister about 54 years.--(See _Piety Promoted,_ Part vii.)]
who had the like concern.
We went to Colchester, and thence to Harwich, where we took shipping:
and it was showed me we should meet with some exercise on the coast of Holland;
which accordingly we did.
For after we made land, we took up a ship that was turned adrift,
which had neither men nor goods in her, a Turkish pirate having taken both.
Soon after, we came in sight of the Turkish vessel, which made after us;
and our men began to be afraid, and altered their course,
in order to make for a point of land that was in sight; for the master said.
He would venture our lives and the ship before we should be taken captives by the Turks.
My mind being inwardly retired to the Lord, he showed me,
he would not suffer them to harm us; and that was the strait, which I had a sight,
we should meet with.
So I desired the master to alter his course and stand for the harbour;
but he was very unwilling; although, after some entreaty,
he gave orders to bear up the helm and steer for the harbour.
Then the Turks altered their course, and we escaped,
and got safe to our desired port at the Brill;
having seen the Lord`'s power made manifest in
preserving us from the hands of unreasonable men;
which brought us under a renewed obligation to bless and praise his name.

The next day, we took our journey for Rotterdam,
and the day following had a meeting there, and spoke to the people by an interpreter,
which was something hard for us; yet the Lord, who called us into his service,
fitted us for it by his living power,
and was effectually with us to the bearing up of our spirits,
and settling them into such a frame as the service required.

After the meeting was ended, we took our journey to Amsterdam,
arid were there at the time of the yearly meeting.
We had many heavenly seasons together; the Lord overshadowed us with his love;
and in that, our hearts were bound up with him, and one with another.
In that city we had much exercise of spirit;
for many people resorted thither from several parts, and some were reached by the Truth.
And after the meetings w`'ere over, the interpreter told me of a city called Horn,
in which there was a people inquiring after (the Truth; which I was glad of,
for I had a concern for the place before I left my outward habitation.
So we took our journey to Alkmaer, and had a meeting there; then went to Horn,
where we were gladly received by a sober people,
who had never been visited by Friends before, and were willing to have a meeting with us.
A meeting was held accordingly, and the Lord favoured us with his heavenly power,
whereby we were enabled to proclaim the everlasting gospel amongst them;
which so affected their hearts that several confessed to the Truth.
We came away in peace, took our voyage for Friesland, and travelled through it,
having several meetings amongst the people:
the Lord`'s heavenly power and presence still attended,
and preserved us both by sea and land; for which we were truly thankful to him,
who is God worthy for ever.

Then we went to Groningen; also to Embden, and had a meeting there,
to which many of the magistrates came.
When we were clear of that city, we returned back to Amsterdam;
and the Lord was pleased to go along with us, and sweetened all our exercises,
I went to the Jews`' Synagogue,
and had a dispute with one of them in the audience of the people.
He acknowledged what I spoke was true:
I was concerned to speak of the new covenant which God
promised he would make with the house of Judah and Israel,
Jeremiah 31:33, that He would write his law in their hearts,
and put his Spirit in their minds; and the law is light, and the commandment a lamp,
and the reproof of instruction is the way of life.
Then I asked him,
If he did not find something in the secret of
his heart which reproved him for sin?--He owned,
he did.--I told him, _That_ was the appearance of the Spirit of Christ,
which reproves for sin and unbelief.
Then he asked me.
If the law was not good, and what I thought concerning their worship?--I answered,
I may say, as the Queen of Sheba said, when she went to see the wisdom of Solomon,
and the order that was in his house, that one half was not told her;
so though I had heard of their rudeness and lightness in their devotion,
yet one half was not told me, of what my eyes had seen that day.--I reproved them for it,
and came away in much peace.

Then we came to Rotterdam, and took shipping for Colchester in England.
In our voyage we were in danger by reason of a great storm;
but we saw the wonders of the Lord wrought for our deliverance,
and got safe to our intended port; so that we may say, the Lord is large in his love,
and of great kindness to them that are truly given up to follow him.
Then we travelled to London, where we had deep exercises with several bad spirits;
but the Lord was with us, and enabled us to bear our testimonies against them,
and for the Truth, and those that lived in obedience thereunto;
amongst whom we were truly comforted,
finding Truth to prevail and righteousness to flourish,
which was what our souls travailed for.

Having cleared ourselves of that city, we proceeded to Reading,
and had some service there; at which place I parted with my companion;
then travelled into Oxfordshire, and visited Friends:
the sweetness of the love of God was felt in their assemblies,
which occasioned praises to be sounded forth to his name.
From thence I went to Bristol and Ross; also to Monmouth,
where I had a meeting in the market house, to which many people came:
some were very rude and cast a fire-ball at me; but the Lord by his power preserved us,
so that it did neither me nor any there harm.
He gave me power to proclaim his everlasting gospel,
and enabled me to set the testimony of Truth over the heads of the opposers of it;
so that they became very sober, and I had time to clear myself amongst them.
After the meeting was over, they desired me to have another, and said,
I should have no disturbance: but finding myself clear,
I went from thence and travelled through South Wales, visiting Friends`' meetings;
and the Lord was with me to my great comfort.
Then I went to Cardigan along with another Friend;
and we had a meeting in the Sessions House, to which came the mayor, aldermen,
and several people of the town.
The Lord was with us, and gave strength and ability to proclaim the gospel amongst them;
by which several hearts were tendered and reached;
many confessed to the Truth and invited us to their houses.
We went to visit them, and had a dispute with a high professor,
relating to our principles and doctrine: the Lord stood by us,
and gave us wisdom to answer such things as were objected against us;`" and
the people went away generally well satisfied.
After this meeting, I travelled into North Wales, and visited Friends;
and was refreshed amongst them in the love of God.
At Dolobran I met with Thomas Wilson and William Greenup,
who were travelling towards Bristol; we had several meetings together,
and were sweetly refreshed in the love of God;
after which I returned home and staid some time.

Then finding my heart engaged to visit Friends in Yorkshire,
I went in company with another Friend to York, where I had many precious meetings;
and a concern came upon me to visit those that had gone
out from amongst Friends into a contentious spirit.
In obedience to the Lord`'s requirings I went;
and warned`' them to repent and return unto the Lord whilst he strove with them,
lest their day of visitation should pass over, and it might be said,
as it was to Ephraim, "`Let him alone,
he is joined unto idols:`" but it may be said of them as it was of some of old,
that "`they went out from us, because they were not of us, for if they had been of us,
they would no doubt have continued with us; but they went out,
that they might be made manifest they were not all of us.`"
After I had cleared myself, I came away in true peace of soul,
travelled through the east of Yorkshire, Durham, and Northumberland, and visited Friends;
then returned home,
and had many precious meetings amongst my brethren in the love of God.

Some time after,
I had a concern upon me to visit the churches of Christ in the nation of Ireland:
so I went to Whitehaven, and took shipping for Dublin.
The ship`'s company were high professors,
and there was also a Presbyterian preacher on board.
They began to reflect against Friends and their principles;
but the Lord gave me wisdom and ability to set the Truth over their heads,
and to prove our principles by Scripture; which bowed me in thankfulness to the Lord,
who never forsakes those that are truly concerned for his Truth and glory;
but bears up their spirits in all exercises,
and carries them through to the exaltation of his own name.
We landed safe at Dublin, where I met with my dear companion Thomas Wilson,
and many other travelling Friends from several parts of the nation,
who were come to the half-year`'s meeting, which was very large: a blessed,
heavenly meeting we had, in the enjoyment of God`'s love.
Friends being in sweet unity one with another.
Our hearts were filled with joy and gladness; and many living testimonies were borne,
with heavenly exhortations one to another,
to be faithful and walk worthy of the Lord`'s tender mercies;
that so they might be continued unto us, and we in the enjoyment of them,
might grow in the life of righteousness as God`'s heritage and husbandry,
and bring forth fruits to his honour.
After several days spent in such exhortations,
and taking inspection into the state and affairs
of the churches of Christ the nation over,
the meeting ended in a sense of God`'s love, with hearts full of praises to his holy name.

After the meeting I travelled through Wicklow and Wexford,
to the provincial meeting at Limerick;
and the Lord was graciously pleased to go along with me,
and strengthened me with his living presence,
whereby I was enabled to answer his requirings.
From thence I returned to the provincial meeting at Rosenallis,
where I met with John Burnyeat, who was as a tender nursing father to me:
we had many heavenly seasons together.
I travelled into the north, where I visited Friends,
and laboured in that ability God gave me; warning and cautioning people to repent,
and turn to the Lord whilst the day of their visitation lasted;
advising Friends to faithfulness, and to mind their settlement in the Lord`'s power,
that would remain when all other things might fail.
Then finding myself clear, I returned to Dublin, and took shipping for Whitehaven,
where I arrived safely and staid some time.

Afterwards I went into North Wales, having another Friend in the ministry along with me;
and the Lord enabled us to proclaim his everlasting gospel,
whereby many hearts were reached, and the churches of Christ confirmed.
When we had visited North Wales, we travelled into the south parts; into Pembrokeshire,
Glamorganshire, Monmouthshire, and so to Bristol, Somersetshire, Devonshire,
and Cornwall; and had good service.
Great exercises attended us in divers respects;
the nation was in confusion by reason of the revolution of government,
which happened at that time, and the devouring sword was drawn; but the Lord in mercy,
to the people, restrained it.
We laboured in the love of God amongst them,
for the turning of their minds to the light of Christ Jesus;
that thereby they might come to know him to rule over them, and that Scripture fulfilled,
that though "`every battle of the warrior is with confused noise,
and garments rolled in blood; but this shall be with burning and fuel of fire.
For unto us a Child is born, unto us a Son is given:
and the government shall be upon his shoulder: his name shall be called Wonderful,
Counsellor, the Mighty God, the Everlasting Father, the Prince of Peace;
of the increase of his government and peace there shall be no end.`"--Isa. 9:5-7.
Blessed be the name of our God,
many can say he rules in their hearts, and is teaching the same lesson now by his Spirit,
that he taught his followers when in that prepared body,
even to love and pray for their enemies;
and these know his kingdom (as he said himself,) not to be of this world,
therefore they cannot fight; but are subject to the royal law,
to do to all men as they would be done by.
In this peaceable spirit we travelled,
and laboured to preach the gospel in many parts of this nation.
So came to London to the yearly meeting, where Friends from several parts were;
and the Lord, by his heavenly power, overshadowed our souls,
and opened the fountain of wisdom amongst us, which was in many as deep waters,
and flowed through them to the refreshing of God`'s heritage;
in a sense of which the meeting ended.
After we had travelled through Sussex and Kent, I, with my companion, returned to York,
and was at the yearly meeting there; then went home, where I staid some time.

Finding drawings in my mind to visit the churches of Christ in the east of England,
I travelled into Lincolnshire, and some other parts; then into Nottinghamshire,
Leicestershire, Warwickshire, Gloucestershire, and so to Bristol,
where I met with my companion Thomas Wilson.
We travelled together as far as the Land`'s End, and had good service in several places,
having meetings in towns where none had been before.
I came back by Bristol, into WaleSj through Gloucestershire;
and through some parts of Oxfordshire, by London to Surrey, and Hampshire.
After I had visited Friends in those counties,
I returned to London to the yearly meeting, where I met with many brethren;
and we were comforted in the Lord, and had sweet unity and concord together.
After the meeting, dear John Tiffin,^
footnote:[John Tiffin, who resided at Mockeskin, near Pardshaw in Cumberland,
travelled at various times in the work of the ministry.
In the year 1654 he went to Ireland.
At that early period in the history of Friends,
there were but very few of them in that nation; with these few,
and in endeavouring to promote the further spreading of the Truth,
John Tiffin spent five or six weeks.
His ministry was at that time, in few words, but edifying and very serviceable.
He attended the small meeting held in William Edmudson`'s house at Lurgan,
(the first settled meeting of Friends in Ireland,) and
travelled with him to several places:
they had good service for Truth, although through great opposition.
At Belfast, the inhabitants shut their ears, doors, and hearts against them;
yet this did not hinder them from holding a meeting near that town, in the open air.
They sat down, and kept their meeting in a place where three lanes met,
and were a wonder to the people who came about them;
and something was spoken to direct their minds to God`'s Spirit in their own hearts.
These exercises, though in much weakness and fear, spread the name and fame of Truth;
thereby many honest people were induced to inquire after it,
the number of Friends increased in those parts,
and some were added to the meeting at Lurgan.
In the next year, John Tiffin, visited Ireland again, with James Lancaster.
At a meeting held on the green at Lurgan, in the course of this visit,
these Friends and William Edmundson met with much personal abuse.--
See Rutty`'s _History._
{footnote-paragraph-split}
In the year 1676, John Tiffin,
accompanied John Burnyeat through Westmoreland and Yorkshire, to London;
and in 1684, into the north of England and Scotland.
See Whiting'`'`s Memoirs.
He also took a short journey with James Dickinson in 1695.
See page 386 _Friends`' Library,_ Vol.
12. He died in the twelfth month 1700-1.]
a Friend in the ministry, and I, travelled through Berkshire and Wiltshire to Bristol;
from whence we returned home in peace,
with true thankfulness for the Lord`'s continued favours.

In the year 1690, I had a concern upon me to visit Friends in Scotland,
and in company with another Friend, travelled into the west, where we had good service.
Then we crossed through the country to Edinburgh,
where many hearts were reached by the Truth.
From thence we went down into the north to Robert Barclay`'s at Ury;
he travelled to Aberdeen with us, and through the north and visited Friends.
It was a time when there were great troubles in the nation,
but the Lord preserved us every way;
and we returned to Robert Barclay`'s house to a general meeting.
At that time, dear Robert Barclay took the sickness,
of which a few days after we left his house, he died.
I was thereby sorrowfully affected,
in consideration of the loss the nation would have of him;
but our loss is his everlasting gain.^
footnote:["`James Dickinson visited Robert Barclay when on his death-bed:
as he sat by him the Lord`'s power and presence bowed their hearts together,
and Robert Barclay was sweetly melted in the sense of God`'s love,
and with tears expressed his love to all faithful brethren in England,
who keep their integrity to the Truth; and added,
'`Remember my love to Friends in Cumberland, and at Swarthmore,
and to dear George,`' meaning George Fox,
'`and to all the faithful everywhere;`' and further said, '`God is good still,
and though I am under great weight of sickness and weakness as to my body,
yet my peace flows; and this I know, whatever exercises may be permitted to come upon me,
it shall tend to God`'s glory and my salvation; and in that I rest.`'
He died the 3rd of the eighth month, 1690.`"--__Piety Promoted,__ Part iii.]

After having travelled and laboured in the work of the gospel,
through many dangers both inward and outward,
we returned home as with sheaves in our bosoms; being truly thankful unto the Lord,
in that he had preserved us out of the hands of unreasonable men,
and assisted us by his Spirit to answer his requirings: we found true peace to flow,
and a willingness wrought in our hearts to follow Him wherever He was pleased to draw us,
who is known to go in and out before his people; blessed be his name for ever.

On the 23rd of the eleventh month 1690, I took my journey for London.
At Swarthmore, I met with the tidings of the removal of our dear friend George Fox,
which occasioned deep sorrow in my heart: but when I turned my mind to the Lord,
I found he had done the work of his day, and was gone to rest; and we must be content;
and they would be happy that followed his footsteps.
I proceeded to London, visiting Friends as I went; from thence to Kingston,
where I met with my companion Thomas Wilson.
We returned to London, and afterwards went into Essex, Suffolk,
Norfolk and Cambridgeshire, and had good service for the Truth:
then returned to London again, where we staid the yearly meeting,
and were truly refreshed in the love of God with our faithful brethren.

After the yearly meeting, I, with my dear companion Thomas Wilson,
took our voyage for Barbadoes; a concern having been upon me for many years,
to visit Friends in America.
The fullness of time being come,
a willingness was wrought in my heart through the power of God,
that I freely gave up to answer his requirings;
having experience he had not failed to help in the midst of imminent dangers:
such were very apparent at that time, the English and French being at war.
We left London on the 13th of the fourth month, 1691.
Many Friends accompanied us down to Gravesend, where we had a meeting next day,
and took our leave of Friends in much love and tenderness.
The day following we went on board the ship and sailed to the Downs,
where we (staying some days for the fleet,) went
ashore and had several precious meetings:
the Lord`'s power was manifested to our great comfort;
by which we were made willing to take our lives as in our hands,
leave our native country, and all in this world that was near to us,
in obedience 1o his pure will.

From hence we set sail, and touched at Plymouth and Falmouth,
where we went ashore and had several precious meetings:
the Lord`'s wonted presence was witnessed, and we were comforted with our Friends;
praises be to his holy name for ever.
We set sail from Falmouth on the 9th of the fifth month,
and lost sight of land that night, being eighteen sail in company.
After we had sailed a few days, we met with the French fleet,
consisting of sixty or more vessels: they came up with us, fired several times at us,
and laboured to compass us round;
so that there seemed little or no hopes for any of us to escape.
But our cries and supplications were to the Lord, by whom deliverance comes,
and true help is known in the time of need: and he, in this strait,
made manifest his power; and in an unexpected way to the eye of reason, deliverance came.
We were not so much concerned for the loss of any thing in this world,
or the cruelty they would inflict upon us, as for the honour and reputation of his Truth;
lest the enemies thereof should falsely vaunt
themselves and say,--that God whom we served,
was not able to save and carry us through in our service.
But the Lord, who sees the sincerity of all hearts, showed his wonders;
according to that saying of the Psalmist, "`they that go down to the sea in ships,
that do business in great waters, these see the works of the Lord,
and his wonders in the deep:`" for the Lord heard us and granted our request,
when most of our visible hopes were gone.
After all our fleet had struck and were taken by the French,
except our ship and two others, and they were coming up to take ours,
about the first hour in the afternoon, a thick fog came on and spread around us,
which prevented them in their design.
The fog continued for about four hours; then it became clear,
and we discovered a large ship to windward, which was one of the French fleet.
She bore down upon us; but before she got up with us,
the fog came on again and encompassed us about: afterwards the night came on,
and we saw her no more.
Then, not only ourselves, but all the ship`'s crew, confessed it was the Lord`'s doings.
Next day we espied two ships to leeward, to which we hoisted English colours,
and they answered; being the two of our own company which had escaped the French.

When first-day came,
the masters and several of their crews and passengers of the other two ships,
came aboard ours, and we had a meeting on the quarter-deck: the Lord`'s power was with us,
and Truth`'s testimony was declared amongst them: several confessed thereto;
and our hearts were broken in a sense of God`'s love and wonderful mercies,
that overshadowed our souls in secret retirement, upon the deep ocean.
The captain of our ship was a very loving, kind man to us.

When we came into the latitude of Barbadoes, a ship to-windward bore down upon us,
which our master took to be a French privateer.
He made preparation to fight her, and ordered all the passengers but Thomas and I,
to take their quarters; saying to us, '`As for you,
I know it is contrary to your principle to fight;
Lord forbid I should compel any man contrary to his conscience! take your
quarters with the doctor;`' at which the other passengers were angry.
I told them,--To show it was not cowardice but conscience,
we would take our quarters upon the quarter-deck;
which set the testimony of Truth over them, and they were quiet.
When the ship came up with us, it proved an English vessel.
We proceeded on our voyage, and landed at Bridgetown in Barbadoes,
on the 24th of the sixth month.
We found the hand of the Lord upon the inhabitants of that island,
in visiting them with great sicknesses, of which many hundreds died.
Our hearts being filled with the love of God,
we were largely drawn forth to proclaim the everlasting gospel to the people;
and although the sickness was very infectious, and many that went over with us died,
yet the Lord preserved us, and we went on in our service: he was effectually with us,
and by his power the inhabitants of the island were alarmed.
People flocked to our meetings, and they were full and large; many were convinced.
Friends confirmed, the mouths of gainsayers stopped,
and the hearts of the faithful were made truly glad.

When we had travelled the island several times over, finding our spirits easy,
we returned to Bridgetown; were at their general meeting,
and had a fine season to take our leave of Friends;
cautioning them to live in unity together, and to keep in the one Spirit,
that would keep them in one mind; in which they would appear as lilies among thorns,
and grow in the life of righteousness: in much tenderness the meeting ended.
The ship being under sail, we went to the water side, many people accompanying us.
We were broken and tendered together in the sense of God`'s love;
and in much bowed-downness of spirit,
our hearts were filled with praise and thanksgiving to the Lord God and the Lamb.
We set sail for New York, on the 22nd of the eighth month,
and had a comfortable voyage till we came near the coast of the main land,
where we met with a north-west storm;
but through some difficulty arrived in New York harbour, on the 23rd of the ninth month.
From thence we went to Long Island, and were at a general meeting,
which was very large and full:,
our hearts were knit together in the love of God and unity of the one Spirit.
We visited Friends generally in the island,
and found great openness to preach the gospel of salvation unto the inhabitants thereof;
for the Lord was with us, and was pleased to be mouth and wisdom to us,
for the convincing and settling of many upon the Rock, Christ Jesus,
who is a sanctuary to his people, where they dwell safely,
and are quiet from fear of evil.

Being clear of the island, we took boat at New York and passed over to East Jersey,
where we had many heavenly meetings.
After we had visited Friends in East and West Jersey,
and had good service among the people, we went into Pennsylvania,
where meetings were full and large.
Our hearts were opened, and strength was given to publish the word of God:
he bore up our spirits in deep exercises, in our inward wrestlings and outward travels.
It was the depth of winter, and meetings were held without doors,
sometimes when there was deep snow;
the meeting-houses not being large enough to contain the people.
There is a tender-hearted people in that country, who love the Lord:
we laboured and travailed for their growth and settlement in the Truth.
After having had many heavenly meetings among them,
we felt pressed in our minds to get on our journey.
We travelled through the woods and wilderness in deep snow;
and passed through many dangers in crossing the rivers upon the ice,
until we came to Chester river in Maryland.
Here we met with a few Friends, and had a good meeting among them.
From thence we went down to Choptank, and visited Friends there;
then took boat over Chesapeake bay to the western shore in Maryland.
It was hard frost, and we had to wade deep among the ice to get forth of the boat,
because the sands prevented it from coming to the shore.

Having got safely to land, we were the next day at their quarterly meeting;
where we laboured for the stirring up of all to righteousness,
and that nothing might be given way to,
that brings a reproach to our holy profession and pollutes the camp of God;
also that our unity might be kept in the bond of peace.

When we had visited Friends on that shore, we took boat to cross the bay again.
Night coming on and a thick fog, we missed our course and w`'ere cast upon an island;
where we got to a house and lay on the ground among the negroes until next morning:
then we set forward and got to the other side, and visited Friends.
From thence we travelled to the eastern shore in Virginia;
having to pass over many dangerous rivers in boats and canoes.
But the Lord still continued his mercies to us and his care over us,
and many times manifested his power for our deliverance.
Being clear of at side,
we crossed Chesapeake bay to the western shore in Virginia with some difficulty,
and landed from James river.
Next day we took our journey, visited Friends, and had good service.

Then we proceeded through the wilderness to Carolina;
where the floods were so great that we could not travel on horseback,
but waded barefoot through swamps and waters for several miles.
Friends and other people were glad to see us,
they not having had any visit from a travelling Friend for several years before:
we had many comfortable meetings among them.

After we were clear,
we took our journey back through the wilderness
to the general meeting at Chuckatuck in Virginia.
We warned them to keep out of the superfluous fashions of the world,
which had too much prevailed among many.
The Lord, by his power, broke in upon the meeting,
and the entrance of his word gave life: the weak were confirmed, the faithful comforted,
and judgment placed upon the head of the transgressor
and that spirit of separation which was among them.

After we were clear of those parts, we went towards the falls of James river;
where we found a great openness among the people, several being convinced:
we laboured in love for their settlement, in the Truth, and the blessed order thereof:
they were very willing to hearken to counsel, and received us gladly.
From thence we went through the woods to Black creek,---a place which
had not been visited by Friends before,--and had a meeting there;
to which the sheriff`" and some officers with him came.

When I was declaring the Truth among the people, the sheriff asked me.
By whose authority I came there?--I told him,--In the authority of the great God,
to whom we must give an account.--After some discourse,
he commanded us to leave the meeting;--I desired him to show his moderation,
and hear what we had to say; upon which, he and the officers went away,
and we kept our meeting quietly, and several were reached by the Truth.
After the meeting, we took our journey towards Maryland,
and travelled about a hundred miles through the wilderness without a guide,
except part of`" the first day.
That night we lodged in the woods, where we made a fire against the cold,
and to keep the wild beasts from us; it being in the first month, and very cold weather.

Next morning early we set forward, and travelled most part of the day.
Near the evening we met with two men: one of them who was a justice,
kindly invited us to his house, it being about ten miles distant: we went along with him,
staid two or three days at his house, and had a meeting there:
the justice was very loving and confessed to the Truth.
Then we passed over Potomack river in a small Norway yawl,
where I swam my horse three miles.

We travelled through the woods to Patuxent river;
passed over to the western shore in Maryland, with much difficulty, danger, and charge;
and had many comfortable meetings in those parts.
We then crossed Chesapeak bay,
and travelled hard to get to the yearly meeting at Salem in Jersey,
which was held in the second month.
Here we met Friends from most parts of the country; had many glorious meetings;
and were livingly opened to proclaim the everlasting
gospel and day of God`'s love to the mourners in Sion,
encouragement to the weak and feeble, and judgment to the fat and full.
The meeting ended in love and unity, and our hearts were filled with praises to the Lord.

After the meeting at Salem, we went, in much bowed-downness of spirit, to Philadelphia,
where George Keith had drawn several out from Friends into a separate spirit,
to the dishonour of Truth and themselves.
But the Lord was pleased eminently to favour us with his power and presence:
he was mouth and wisdom to us,
and enabled us to set the testimony of Truth over all the opposers of it,
so that many hearts were reached and confirmed therein.
(For a more full account,
see Thomas Wilson`'s Journal.) When we were clear of those parts,
we set forward with several other Friends, to the yearly meeting on Long Island.
We found Friends there in sweet unity, and had many heavenly meetings;
many hearts were tendered by the Lord`'s power,
and the meeting ended in a sense of his love.
After having had meetings at several other places on
the island,--to which many people flocked,
and in which our hearts were opened to proclaim the gospel of
life and salvation,--we took ship for Rhode Island,
and landed there the day before the yearly meeting began.
Friends received us in that love by which we were drawn to visit them.
We were many times favoured with the flowings of the pure life:
the Lord overshadowed our souls, opened the fountain of his wisdom,
and caused his doctrine to drop as the dew.
The faithful were comforted, the careless awakened, and the wicked warned to repent.
Friends were stirred up to keep to the heavenly order of the gospel;
to support their testimonies in the life of Truth;
to be careful to watch over one another for good; to keep in the love of God;
and to train up their children in the way of Truth.
When we had thus laboured and eased our spirits, we found the Lord near us,
watering our spirits with the showers of his love;
and our hearts were filled with thanksgiving to his most worthy name.

Then we travelled into Plymouth colony, in New England,
and had many precious meetings amongst the professors:
some were sober and were convinced, but others remained in their persecuting spirit,
rejecting the Truth.
At Sandwich, the priest came and disputed with me about religion; at first,
he seemed pretty moderate, but I was concerned to lay open his deceit,
at which he grew peevish: then my companion had much discourse with him,
and he was made to confess to the Truth.
After which we went to Yarmouth, and found a tender-hearted people,
and had service among them.
As we returned, I overtook another priest on the road; he put several queries to me,
which I answered, and he confessed it was Truth.
When we were about to part, he asked, Where I was going?--I told him,
To Boston;--he said,
He had known a time when it would have been a dear going there for me.--I told him,
That was no credit to them,
and that God would require it at their hands:--to which he confessed, and said,
He was always against persecuting the Quakers,
for which he was envied by many.--I asked him.
If he had ever declared his mind in writing to the world,
and denied such bloody practices'`?--He answered, He had not;
but at all times appeared against it.
So we parted from him and travelled to Boston,
and had many public meetings in that place:
but the hearts of the people were so hard and set against the Truth,
notwithstanding the judgments of God which were fallen upon them for their wickedness,
that few of them would receive our testimony.
After we had visited Boston and Salem, and the meetings thereabout,
we returned to Rhode Island, and had several precious meetings there.

Then we returned to Boston and Salem; so to Hampton,
where the people had left their habitations and were gone into forts,
for fear of the French and Indians; who had burned several towns,
and carried many of the people captive to Canada.
In this time of great fear, we found an openness among the people,
and had a time to clear ourselves: after which we returned,
not without some danger,--the Indians having taken and
killed people on the road that day--to Salem and Boston.
Then an exercise came upon us to visit the Narraganset country, where no Friends dwelt;
we therefore proceeded through Plymouth colony, and had several meetings.
At Warwick we had a large meeting, and several were convinced of the Truth.
After which we travelled to Providence yearly meeting.
Many hundreds of people were there: the Lord`'s power eminently broke in amongst us,
and our hearts were melted together.

After the meeting we took boat, and passed over to Rhode Island;
where we had to stir up the people to faithfulness.
We then went into the Narraganset country, and had good service there;
several were convinced, and the mouths of gainsayers stopped.
The Lord`'s power and love sweetly overshadowed us, and when our service was over,
we left with sheaves in our bosoms,
and returned to Boston in order to take shipping for Barbadoes.
During our stay at Boston we had several meetings: Truth broke through and made way,
whereby we were comforted amongst Friends; praises be to the Lord for ever.

On the 17th of the sixth month, 1692, we took shipping at Boston for Barbadoes.
After we had been some days at sea, our vessel sprung a leak,
and our pumps would not clear her.
Upon search, we found the place and got it stopped.
In the night following, we met with a great storm, which continued for three days:
most of the ship`'s crew concluded we should be cast away;
but the Lord remembered us in mercy; for he rebuked the winds and the seas,
and filled our souls with the joy of his salvation.
The master of the ship and company were great professors,
and enemies in their minds to us and our principles: we had some discourse with them,
and the Lord gave us wisdom to stand in our testimony, and keep our peace.
The master said.
If he was taken by the French, it would be because he had the Quakers on board.
But though there was a privateer in the latitude of Barbadoes,
we landed safe at Bridgetown in that island, on the 2nd of the eighth month.

After the ship had staid a few weeks, they put to sea again;
and she was taken in sight of the island in their return, when no Quakers were on board,
and carried to Martinico by the French;
which might plainly convince him of the erroneous judgment he had,
relating to the Quakers.

Friends in Barbadoes were glad to see us, and we them.
The hand of the Lord was still upon the inhabitants,
and many were taken away by death in sore distempers:
also the negroes at that time made a plot,
intending to kill all the white people in the island: but it being discovered,
they were prevented; although the white people were in great fear.
We laboured amongst them in the love of God, and his presence filled our assemblies;
by which the hearts of his people were greatly tendered:
many that were strangers to the operation of Truth in their hearts,
were reached by the power of God, and we favoured and preserved,
both inwardly and outwardly.
Friends were in sweet unity and concord, and in much tenderness we parted with them.

On the 19th of the ninth month we took shipping for Antigua,
and landed there on the 23rd of the same.
We found a few Friends, who were glad to see us: but the inhabitants were very wicked:
yet the love of God was largely extended towards them,
and we laboured in that ability given unto us; which so affected their hearts,
that several were reached by the power of God, and received the Truth in the love of it,
during our stay there.
Having cleared ourselves of the work and service which the Lord required of us,
on the 30th of the tenth month, we took shipping for Nevis.
The next day after we had set forward, we narrowly escaped a French privateer,
which was upon the coast and took a ship out of the harbour that night:
we could not but admire the Lord`'s mercy in
preserving us from the hands of unreasonable men;
and our hearts were truly thankful unto him for his manifold preservations.

Friends of the island having intelligence of our coming there,
two of them were upon the shore waiting for us, who received us kindly.
We staid some time on the island: the Lord`'s hand had been heavy upon the inhabitants,
and had numbered many of them to the grave by a malignant distemper.
Our hearts were opened to proclaim the everlasting gospel amongst them,
and we warned them to repent and turn to the
Lord whilst his visitation was extended to them.
Many hearts were reached by the power of God, and made to confess unto the Truth;
and we found our peace continued and increased with the Lord.
And when we were ready to go out of the island, we went to the governor,
in order to have our certificate signed by him; but he refused and said.
We should not go off the island.
So we left him,
and told the master of the vessel with whom we had agreed for our passage,
who said he would go with us to the governor: a sober man that was a justice,
wrote to him also on our behalf.
When we appeared again before the governor, he seemed very high;
yet after some discourse, said.
For the master`'s and justice`'s sakes he would sign it; but as for us,
we might be spies.--I told him, We were no spies, but true men,
and did not come out of England unknown to the government.
Then I showed him a pass which we had from the Secretary of State,
wherein the governors of the several islands within the dominions of England,
were commanded to let us pass: after which he seemed very kind, and asked.
Why we did not show him it before?--We told him, We had not shown it then,
but to satisfy him we were true men,
and came in the love of God to visit the inhabitants: so we parted very friendly.

We took shipping for Whitehaven, on the 26th of the twelfth month, 1692;
and as soon as we got on board the vessel,
the Lord wonderfully favoured us with his living presence,
which caused tears of joy to flow.
We landed safe at the Highlands in Scotland, on the 15th of the second month, 1693,
and from thence travelled into Cumberland, home.
