== Chapter II.

[.chapter-synopsis]
* Religious service in Various Parts of England, Wales, and Ireland
* His Marriage
* A Warning Proclaimed through Many of the Streets of London
* Visit to Some Northern and Eastern Counties
* Epistle to the Yearly Meeting in London
* His Second Visit to America
* Epistle to Friends in the West Indies

After staying a few weeks at home, we took our journey to the yearly meeting at London,
Friends were glad to see us safe returned from America.
After the meetings, which were to satisfaction and comfort of Friends,
I returned homeward, attended the yearly meeting at York, and had good service there;
also visited several other meetings in that county; so into Cumberland, and laboured,
in the ability given, for the stirring up of Friends to their religious duties.

At this time I was engaged with a young woman,
belonging to our own meeting at Pardshaw-Cragg, in order for marriage;
but finding I had some further service to perform
before the accomplishing of our marriage,
I acquainted her therewith: she desired me to mind the Lord's requirings,
and answer them; and not to be any way straitened on her account.

On the Sth of the ninth month, 1693, I took my journey into Westmoreland;
and had a warning to all who were convinced of the Truth,
to keep their minds more inward with the Lord,
that they might know the work of his power to redeem them out of the earth,
and draw their affections more heavenward;
and that the younger sort might be weaned from the delights and vanities of the world.
Then I went to Sedbergh, and through the dales of Yorkshire, to the eastward,
and had good service for the Truth; and went forward on my journey,
by way of Lincolnshire, up to London.

After my service in that city was over, I was drawn into Kent;
where I found many that had been convinced by Truth's testimony,
when I was in that county in the year 1686: several of them were well grown in the Truth,
and I had good service among them.
When I was clear of those parts, I travelled into Sussex and Hampshire,
and found a concern upon me to visit those who
had run out into separation with John Story,
at Reading.
I went to the separate meeting,
and sat down in silence to wait for the motion of the word of life from heaven.
I found them in an exalted mind, above the pure fear of the Lord,
which occasioned my soul to mourn: and although one Charles Harris,
an opposer of Friends, and leader into separation, charged things on me falsely,
which he was not able to prove, yet I cleared myself, and came away in peace of mind,
and went to Friends' meeting.
But that being near over, I desired to have another meeting with them in the afternoon,
to which many of the Separatists came.
The high-minded were judged, and the humble revived,
by the powerful operation of God's love;
and several that had been drawn aside into separation,
signified their satisfaction with the meeting.

From thence I travelled into Dorsetshire, and visited Friends and many people;
warning them to repent and turn to the Lord; exhorting Friends to be careful,
and keep more inward with the Lord, and walk as becomes our holy profession.
When I came near the Island of Portland, where I had formerly been abused,
a concern came upon me to visit the people there:
several Friends went with me from Weymouth.
As we passed through the villages, I exhorted the inhabitants to repent,
and turn unto the Lord, whilst he strove with them.
Some were sober, but others envious; and one man who belonged to the castle, raged much,
and bid me depart out of the island, I reproved him for his behaviour.
He told me, he would fire all the guns in the castle,
and raise the inhabitants to put me out of the island;
but we went on until we came to the place where I had been abused before,
and had a meeting there, to which many of the inhabitants came,
I preached unto them the way of life and salvation,
by and through the demonstration and power of God.
Whilst I was speaking, the man who belonged to the castle,
came with a drawn sword in his hand, and made several passes at me;
yet had no power to hurt me.
A Friend spoke to him, and told him,
he unmanned himself in offering to strike at one that would not strike again.
Then he seemed ashamed, and was somewhat sober; and after having cleared myself,
I went away in great peace.

Thence I travelled through Somersetshire and Bristol, to the yearly meeting in Wales,
where I met with my dear companion Thomas Wilson; also William Greenup,
and Friends from most parts of Wales.
We had a sweet, refreshing meeting, the Lord's power was manifested to our great comfort,
and the affairs of the church were managed in much love and tenderness.
A godly zeal appeared in Friends against everything
that would bring a dishonour upon the holy Truth,
and scandal upon our profession:
many living testimonies were borne both in the Welsh and English tongues:
a sweet harmony of love and life attended us,
and we were comforted in the Lord and one another.
We had good service at that meeting in helping Friends in discipline;
and the meeting ended in the love of God.
Tidings having reached us of the death of John ap John's wife,
it was on my mind to attend the burial; and I went accordingly.
Many people of various opinions were there;
and I had a concern to publish the everlasting gospel.
The Lord was with me, gave me his word and strength to publish it;
and his power was over all.
Then I went to Bala, and had a meeting.

After my service in Wales, I took shipping at Holyhead for Dublin; where I landed safely,
it being near the time of their national half-year's meeting.
I staid in Dublin till it was over; then travelled into the north,
and warned Friends to keep more inward with the Lord,
and wait to feel the operation of his power to cleanse their minds and hearts.
I travelled hard, and had good service;
the minds of people being much humbled by reason of the
great calamity which had happened in that nation,
many habitations being left desolate by the late wars.
I travelled into Leinster and Monster, and had good service;
many hearts were reached by the power of God, and several convinced of the blessed Truth.
Now finding myself clear of the work the Lord called me unto in this nation,
I returned to Dublin, it being about the sixth month, 1694,
and took shipping for Whitehaven.
In our voyage, we narrowly escaped a French privateer: after which I landed safe,
and travelled home, having had a prosperous journey in the will of God.

During my stay at home,
I found freedom in the love of God to accomplish my
marriage with the young woman before-mentioned.
In great humility and fear,
I besought the Lord that he would sanctify a married state to me,
and keep my mind out of the entanglements of the world;
that so I might not be hurt as to my service in the work of the ministry,
whereunto I had been called.
In a bowed frame of mind, we laid our intentions before Friends;
and proceeded and accomplished the same,
according to the good order established amongst us.
I saw at that time, something like to creep in amongst us,
that would do hurt in the church, namely,
the making of great provision at marriage dinners,
and inviting many people after the marriage.
I felt a stop in my mind, from making more provision than usual;
and in attending thereto, found true peace.
We came quietly home; the Lord owned us with his living presence,
and his love overshadowed us; blessed be his holy name for ever.

In a few weeks after, I had a concern for the city of London,
which very much bowed my mind: my wife understanding it,
desired me to answer what I believed to be my duty; and said,
she only desired to enjoy what she enjoyed, in God's favour;
which did greatly add to my comfort.
So I took my journey and went to Swarthmore; and proceeding,
visited several meetings on my way.
When I was about twenty miles from London, tidings came of the queen's death;
which put people's minds into some consternation.
When I got to London, I had a concern to go to Westminster meeting;
and there being a large gathering of people of several persuasions,
I preached the everlasting gospel by and through the demonstration and power of God;
warning them to repent, turn to the Lord, and consider their latter end;
showing them that the grave equals all, as to the things of this life;
and the great difference between the righteous and the wicked in the other world;
referring to the parable of Lazarus and the rich man.
Many hearts were reached by the power of God, for it was a day of visitation to them:
the meeting ending in a sense of God's love.
Then the Lord showed unto me that I must go through the streets of that great city,
and warn the people to repent; which deeply bowed my mind;
and I laboured under the weight thereof several days,
and would gladly have discovered it to my brethren in the work of the gospel.
But the word of the Lord came unto me saying, 'See thou tell it to no man,
until thou deliver it as I commanded thee;' which was to begin at Whitechapel,
and go through the main streets of the city, and proclaim this message, Wo!
Wo! Wo! from the Lord, to the crown of pride in this place;
for the vials of his wrath will be poured down upon it:
therefore I am made to warn all people to repent, that the Lord may show them mercy.
I went with this message about three miles through the city;
and in answering the Lord's requirings, witnessed peace to flow in my soul.
His arm was stretched forth for my deliverance,
and gave me strength and boldness to bear my testimony among the people:
and not a hand was lifted up against me.
The consideration of the Lord's dealings deeply bowed my spirit, and made me to say,
he is worthy to be obeyed in all his requirings; for all his paths are paths of peace;
blessed be his holy name for ever.

Being clear of the city, I returned home,
and laboured in the work of the gospel in our county:
then visited Friends in Northumberland and Durham, and had good service.

Having, for some time, had drawings in my mind to visit Friends again in America,
the consideration thereof brought deep exercise upon my spirit,
and often bowed me under a sense of God's love to his heritage and people the world over.
I was made willing to leave all, and follow the motion of his eternal Spirit.
And when I told my wife of the concern which was laid upon me,
she desired me to mind my freedom in the Lord, and let no worldly affairs hinder me;
but answer his requirings: so I acquainted my brethren therewith,
and they had unity with me therein, which was a strength to me.

On the 8th of the ninth month, 1695, I took my journey towards London,
in order to take shipping for America: John Tiffin, Peter Fearon,
and several other Friends accompanied me to Swarthmore:
we staid their first-day's meeting, and were sweetly comforted together.
Next day we attended the burial of Daniel Abraham's younger son:
many people of note in the country were there:
I declared the way of life and salvation unto the people, and many hearts were reached.
The next morning John Tiffin, Peter Fearon, and a young man, went over the sands with me.
John Tiffin being ancient, and taken ill upon the sands,
with much difficulty got to Lancaster; where we met with John Gratton,
and had a comfortable meeting among Friends:
after which John Tiffin and the young man returned homewards.
Peter Fearon and I went towards London, and had meetings at several places,
as at Stockport, Nottingham, and Leicester.
The presence of the Lord bore up our spirits, and kept us near him and one another,
in our travels for the good of God's heritage.

On the 21st of the ninth month, we got to London.
The ships not being ready, we staid in the city about three weeks;
labouring in the ability given us for the gathering people to God,
and settling and building up of those that were already gathered,
into the one Spirit and most holy faith.
Then Peter Fearon returning homeward, I accompanied him to Waltham Abbey;
and so to Hertford, where we had a large and heavenly meeting; then to Hitchin,
and from thence into Bedfordshire, and had several meetings there.
Our labour was, to stir up Friends to faithfulness; and to stand true to God,
and their testimony which they were called to bear for the name of Jesus,
against the hireling priests, and paying of tithes.
After several meetings in that county, we went to Francis Coalman's house at Woburn,
and had an evening meeting there; directing all to the light of Christ,
which was manifested in their own hearts; and several were reached thereby.

The day following, Peter Fearon, who accompanied me in pure love,
so far on my intended journey, returned home:
we having travelled together in true brotherly love,
our hearts were knit in the fellowship of the gospel,
which made our parting very affecting.
I returned towards London, being alone; but before I had travelled half a mile,
the Lord's power overshadowed my souL,
by which my heart was broken and filled with joy and gladness;
which made up all m.y wants.
I got to Edward Chester's at Dunstable that night, and had a meeting there.
The next day I went to Hempsted; from thence to Albans; and so to London,
and staid there several weeks, labouring in the word and doctrine of Christ,
and had good service.

On the 8th of the eleventh month, 1695, I went down to Gravesend,
many Friends accompanying me, and two that were going to America.
The next day, we had a meeting on board the ship; and the day following, at Gravesend.
On the first-day of the week, we were at Rochester, and had two meetings:
many testimonies were borne to show forth the Lord's goodness,
and to warn people to repent.
At one of these meetings, a young man appeared in supplication,
whose mouth had not been opened in the ministry before:
I was glad to see the Lord at work in the hearts of babes, to perfect his own praise.
The next day the Friends from London returned home.

On the third-day of the week, being the 13th of the eleventh month, we went on board,
and the day following set sail: the power of the Lord overshadowed my soul;
and my heart was broken under a sense of his goodness,
so that tears of joy flowed from mine eyes,
feeling the glory of his presence to be with me.
Having got the length of the northern buoy, we met with a storm;
therefore came to an anchor and rode two days; then weighed and sailed to Margate Road,
came to, staid next day, and had a meeting on board.
The Lord showed us favour, filled our hearts with joy and gladness,
and living praises to his most worthy name.

Then we proceeded on our voyage, and got into the Downs:
we staid there several weeks for want of a wind, yet were not without service.
There being many Friends' ships there, we had several meetings on board,
so that many had an opportunity, both priests and others,
to hear the gospel preached unto them.
Several priests were going over into Maryland,
having heard that the government had laid a tax
of forty pounds of tobacco on each inhabitant,
for an advancement of the priests' wages;
and many were willing to venture their lives for the sake of the benefit.
The Lord was with us, gave us wisdom to divide the word aright,
both to priests and people, by showing them the way of Truth,
and the difference between those the Lord sends,
and those who run and the Lord never sent, but go for their own ends,
preach for hire and divine for money.
These priests were silenced, and Truth was exalted over all.

Then we went on shore, (I having a great desire to see Friends at Canterbury,
where several had been convinced by the preaching of the gospel,
when I was there before:) we were gladly received, and the next day had two meetings.
When I was preaching, one Cook, a priest, came and staid a considerable time;
the next day he was at the Friend's house where I lodged, and told me.
He was satisfied with the doctrine I delivered, and confessed it was the Truth;
after which he asked me, If I understood Greek and Hebrew?--I told him.
No;--then he asked.
How I understood the scriptures, seeing;
I wanted the original tongues in which they were written?--I answered.
By and through a measure or manifestation of the same power
and spirit the holy men of God were enabled to write them,
which was before the many languages.--Then he said,
He had no immediate impulse to preach:--I asked him.
What he was made a minister of?
and told him, Those who run and the Lord never sent,
never did nor would profit the people; but the apostle's testimony was,
that he and his fellow labourers were "`made able ministers, not of the letter,
but of the Spirit,`" and that was the true fountain of the ministry;
for they that had not the Spirit of Christ were none of his:--to which he confessed,
and said.
He hoped they might have it by succession from the apostles,
but was not sure of it.--I told him,
If I had no immediate impulse of the Spirit to preach the gospel,
I would never have left my wife and family to do it;
but there was a necessity laid upon me, and woe was to me if I did it not;
every true minister of Christ knows a necessity so to do:--the priest assented to it,
and so we parted.
After we had had several meetings up and down in that county to satisfaction,
we returned to the ship; and had meetings in one ship or other almost every day.

When we had staid near six weeks, the wind coming fair, we weighed and stood away;
but the wind turning, we came to again.
Then a great weight came upon me: and I was very much bowed for many days,
under a sense of the power of darkness that was at work.
In a week after, there was a plot discovered, of an intention to kill king William;
and it appeared that the French intended to invade the land,
which occasioned a strict embargo to be laid on all shipping;
so that we were stopped of our voyage near five months.
Yet I had no freedom at all to return home,
but still waited in expectation of getting away.
The Lord was near to me, and often sweetened my exercises;
he bore up my spirit in deep tribulations,
and wrought a willingness in me to give up all.
I was often concerned to go on shore, and travelled in the county of Kent;
was at many meetings and burials there, and had good service.

There I met Thomas Rudd,^
footnote:[Thomas Rudd resided at Wharfo, near Settle, in Yorkshire.
He was convinced of the Truth as professed by Friends, in the early part of his life,
and was soon afterwards called to the work of the ministry.
In this vocation he became a faithful and diligent labourer,
and travelled in many parts of England, Scotland, and Ireland.
He was especially desirous that the camp of God might be kept clean;
and that spiritual Israel might be beautiful,
and in no wise stained with any of the vain customs, fashions,
or corrupt spirit of the world.
In his travels,
he was often concerned to preach repentance and the fear of
God in the streets and market-places of towns and cities,
as well as other places of concourse.
His service in this line often had a good effect; and he was, on certain occasions,
favoured with remarkable proofs of the presence
of that Hand of power which led him forth,
sometimes to the convincing of gainsayers.
For this his labour of love, he was many times imprisoned, sorely beaten and abused:
all which he patiently endured, and like a faithful and valiant soldier,
did not turn his back in the day of battle.
{footnote-paragraph-split}
Near the close of his life,
he rejoiced in having been made willing faithfully to perform these arduous services;
and said, 'It is enough, it is enough that I feel inward peace.
Although I have jeoparded my life many times,
in answering what I believed the Lord required of me, it is all too little.
O! what an excellent thing it is to be at peace with
the Lord and all men.'--He died in the year 1719,
in about the seventy-sixth year of his age.--See _Piety Promoted,_ Part vi.]
who had it upon him to go through several towns to declare the Truth.
At Deal, he was concerned to preach through the streets;
and there being a great concourse of people,
occasioned by the fleet of ships that lay there, many behaved rudely.
I passed through the streets after him, and had dispute with several.
One called a justice was very envious, and said.
He could find it in his heart to put him in prison;--I asked.
For what?
had he done or spoken any ill?
I told him, I was sorry to see any in his place so minded;
for men might and did go daily through the streets cursing and swearing, and drunk,
yet were taken no notice of to be punished: so he was much ashamed and went away.
We had a meeting in the town after that,
to which there came a priest that belonged to one of the men-of-war;
he seemed to be much concerned.

When the meeting was over he spoke to a Friend,
and told him he had a desire to speak with me or Thomas Rudd.
I met with him upon the sea-shore the same night: he being lately recovered from a fever,
was very low in mind, and inquired of me concerning my faith and principles.
My heart was lovingly opened to give him an account of my faith, and Truth's principles;
for I felt the Lord's love greatly abound to the man:
we spent a considerable time that night in conversation.
When I parted with him he was very low, and confessed to the Truth;
desiring to have another opportunity with me or some of the Quakers;
for he had heard strange things concerning us, but he found they were lies,
and we were wronged.

After I had staid several months with the shipping, and thereaway,
I had some drawings in my mind to visit the city of London.
I went thither along with Jacob Fallowfield,
and exhorted Friends to mind their growth in the life of Truth;
for none would be safe but those that knew a growing therein.
We had a very heavenly time,
and found the secret power of the Lord at work in the hearts of several young people.
Many mouths were opened to declare the Truth; for which I was glad,
and to see the Lord's work to prosper.
When we were clear, we took leave of Friends and returned back to the ship.
As we were on the road, we met several who told us the fleet was sailed;
but we found it our place to go forward,
though many turned back upon the road that were going down to the fleet.
We travelled hard, and got there just as they were weighing anchor;
hired a boat and had much to do to get to the ship, she being then under sail.
As soon as the master saw a boat following, he laid the ship by,
and we got well on board, and had a fair wind to Portsmouth:
there we staid above a month, went ashore and had many meetings;
also in the Isle of Wight and at Porchester.
We had good service; several were convinced of the Truth,
and the mouths of gainsayers stopped:
we also had meetings on board the ships to satisfaction; and the day before we set sail,
we had a public meeting on board the ship we went in:
many people came to it out of the country; and the Lord, by his power,
broke in wonderfully amongst us: I was livingly opened to proclaim the word of life,
and many hearts were tendered.
Then I had a sight that the time of our departure was near,
and that we should get on our long-desired voyage.
Next morning the man-of-war put out the signal for sailing; the ships weighed anchor,
and got to Cowes in the Isle of Wight.
We went on shore to Newport, and had a glorious meeting there.
After the meeting was over,
a concern fell upon me to write a few lines to the yearly meeting,
(it beginning the next day after we were to sail;) which was as followeth:

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends, Brethren, Fathers and Elders,

Whom I love in the Lord Jesus Christ, in whom is all your strength, power, and wisdom;
I entreat you all, keep to his eternal power and wisdom,
in the exercise of all your gifts, in this yearly meeting;
that Christ your heavenly head may rule and speak through all,
and carry on that glorious work which he hath begun.
That in the beholding the prosperity of it, your joy may be full in the Lord,
and you be a true strength and comfort one to another,
and to the churches of Christ the world over.
That as the Lord, by his eternal power, did set up those meetings,
and hath honoured them with his presence, he may fill your hearts together,
in this your solemn assembly, with the same power, life, and wisdom; which he will do,
if all keep their places in Christ their heavenly head;
where every one will feel life to spring, and love to abound,
and your unity to be increased one with another.
So may you return to your respective places as with sheaves in your bosoms;
and God over all will be exalted, and the peace of his church preserved;
which is the sincere breathing of my soul to the Lord for you all;
desiring your prayers to the Lord for me, as mine are for you; and in true love,
I remain your friend and brother, according to measure,

[.signed-section-signature]
James Dickinson.

[.signed-section-context-close]
Written on board, near Cowes, in the Isle of Wight, the 29th of the third month, 1696.

[.signed-section-context-close]
Let this be read in the yearly meeting.

--

On the 30th of the third month, we set sail on our voyage to Virginia,
with above a hundred sail in company:
the masters of near twenty of them professed the Truth.
The Lord was merciful to us, bore up our spirits, and sweetened all our exercises.
We had several meetings on board; and when the weather was fair and calm,
we went on board other vessels, had meetings and warned the people to repent;
directing them to the light of Christ, which made manifest their sins,
and reproved them for them; and reminding them what great jeopardy they were often in,
and how soon the great deep might swallow them up and be their grave:
several were reached by the Truth.

About 170 leagues from Virginia, we left the fleet; and in a week after,
got safe into York river, it being on the 23rd of the fifth month, 1696;
but many of the fleet did not get in for above three weeks after,
they having met with a violent storm, and lost several of their masts.
We went ashore at Edward Thomas's at Queen's creek.
My spirit was deeply bowed under the consideration of the Lord's mercies,
and his condescension to us; for he showed me, before we lost sight of the English land,
that I should be in my service that day eight weeks, in America; and it was so,
for we got into Virginia, and had good service for the Truth.
The Lord's power assisted us,
and opened our hearts and mouths to proclaim the word of life to the people.
Then we travelled into New Kent,
where I had formerly visited the people with my dear companion, Thomas Wilson:
several at that time were convinced of the blessed Truth,
and received it in the love of it.
And although I met with opposition from the sheriff and some justices,
yet the Lord's power wrought effectually, and was over them.
After we were gone, they raised a lying report, and told the people we were Jesuits,
and were both hanged in Maryland: several believed it was so;
but those whose hearts were reached by the power of Truth, did not believe it.
We wrote an Epistle,^
footnote:[See _Friends' Library,_ Vol. 2, p. 336.]
to those parts, from Antigua in the West Indies when it came to hand,
it had a good effect for the confirmation of those who were convinced;
and showed to them who believed the report, that it was false.

Friends in New Kent were glad to see us; and notice being given of our going there,
we had a large meeting: the man that had raised the report came in; and when he saw me,
he knew me, and was ashamed: the Lord was with us to our great comfort.
After we had proclaimed the word of life among them, we travelled to Curies:
after the meeting there, we travelled twenty miles to Apomata, and crossed James river.
We swam our horses in the night over Apomata river, and went over ourselves in canoes:
the secret hand of the Lord protected us both inwardly and outwardly;
the sweetness of his love kept us near himself and one another;
and in the strength of his power,
we were enabled to proclaim the everlasting gospel among the people.

We went to Merchanthope and had a meeting there, to which a great number of people came:
the word of life was plentifully declared, and the power of God manifested among them.
A man and woman of note were reached, and confessed to the Truth.
Near the conclusion of the meeting, the priest's wife, with several of his hearers,
came and told me, the priest heard I would gladly speak with him;
and that he was but a little way off, and had a desire to see me:--I replied,
I knew no priest there, neither had any business with any;
and if he heard such a report it was false; but if he wanted any thing with me,
I was willing to give him an opportunity at his request.
So they sent to the priest, and desired him to send for me; which he did.
I went, and several Friends along with me.
The priest and most of his hearers being gathered,
he began to reflect against us and our principles; and said.
We denied baptism, the Lord's Supper, and the resurrection of the dead:--I told him.
His charges were false; so put him to prove his assertions; but he could not.
Then he said among the people.
He did not understand our principles,
but was willing to know our belief concerning those things:--I told him.
He would have manifested more wisdom, if he had known our principles better,
before he charged us with so many errors, and could prove none.
Then I declared our faith;
showing them we believed the resurrection of the just and unjust,
the just to everlasting life, and the unjust to condemnation:
and that we were of the apostle's faith concerning baptism, believing there is one Lord,
one faith, and one true and saving baptism; which is Christ's, to wit,
that of the Holy Ghost and fire.
Then I put him to prove by Scripture, his practice of sprinkling infants but he could not.
He then ran out into many words, charging us with more errors:--I told him,
he ought to prove those he had charged first, before he advanced others;
for if he did not, I thought no wise man would believe him:
but he continued railing against us,
and said that visions and revelations were now ceased,
and no such thing to be known in these days.

Then I desired time to reply; and showed by scripture,
that visions and revelations were not ceased,
and the dismal state of those that knew them not;
for without them there was no true knowledge of God; according to Christ's own words,
"`No man knoweth the Son, but the Father; neither knoweth any man the Father,
save the Son, and he to whomsoever the Son will reveal him.`"
So they that deny revelation, are without the knowledge of God;
for where there is no revelation, the people perish and Elihu said,
"`there is a spirit in man;
and the inspiration of the Almighty giveth them understanding.`"
I desired the people to consider what state they were in who knew no revelation,
and denied that any such thing could be known, as their teacher had done;
"`for if any man have not the spirit of Christ, he is none of his.`"
Then I directed all to the light of Christ, which would give them the knowledge of God,
whom to know is life eternal, according to Christ's own doctrine.
I told the priest, if he would contradict Christ, the prophets, and apostles,
and number himself among those who had no vision,
he manifested himself to be no better than Eli's sons, who had no open vision;
and those the Lord spoke unto by the mouths of his true prophets, and told them,
that night should be unto them for a vision, and darkness for a divination;
and that the sun should go down over the prophets, and the day should be dark over them.
When I had opened these things to the people, I went away;
and afterwards sent several books to be dispersed among the people,
in order to show them our Christian principles concerning
those things the priest had falsely charged upon us.

Then I, with my companion, travelled down to Chuckatuck,
and visited several places there: many people flocked to our meetings,
and we were livingly opened in doctrine by the power of the word of life,
which did plentifully flow to the confirming of God's heritage;
and many hearts were reached thereby.
We laboured to stir up Friends to faithfulness in their
testimonies against those things which were evil;
and to keep to the cross of Christ, that so they might be crucified to the world,
and the world to them; declaring in all plainness,
that a profession of the Truth would stand them in no stead,
except they lived in the life thereof,
and waited to feel the power of Christ working in them to the changing of their hearts;
and knew him to be a mediator and interceder for them to the Father,
and their faith strengthened and confirmed daily; and thereby came to live to God,
and knew the evidence of his Spirit to bear witness
with their spirits that they were his children;
and as such, kept in subjection to him: so would his love fill their hearts,
and bring them under a living concern for his Truth,
and make them zealous for it in their generation; and good patterns to their offspring,
and those that might be seeking the Lord, who were yet strangers to him.

After we had cleared ourselves in those parts,
we got a shallop and went over Chesapeak bay to Accomack, not without some difficulty.
The Lord's love was great to us, and his power manifested for our deliverance;
blessed be his holy name for ever.
We visited Friends on the eastern shore, and had good service.
At one place, there came a great many Indians to a Friend's house where I was;
one of them could speak very good English.
I had some discourse with him about God, Christ, and religion: I asked him,
if he believed there was a God?
He said.
Yes, and that all the Indians believed so too; but he was a Protestant,
and lived amongst the English.
I asked him.
If he knew God?
He answered.
No:--Then I told him,
I would inform him how he might know the great God that made all things:--he said.
He would willingly learn that.
I asked, If he did not find something, when he told a lie, swore, or wronged any,
that let him see he should not do so?
Then he laid his hand upon his breast, with very much seriousness, and said, Yes,
he knew it very well;--I told him.
The great God, that made the Indians, and all things, was a spirit and a great light;
and appeared in the Indians' hearts in order to teach them to be good, and forsake evil;
and if he did but mind that, it would give him the knowledge of God;
for it was the appearance of the great God which showed him his thoughts.
He replied, He did not know that before, but would mind it for the time to come.
Then he asked me, What made the Englishman swear, that knew God was so near?
I told him.
It was the devil which made both the Englishman and Indian bad.
He said.
He never swore before he learned to speak English,
for they had no swearing in their language; but so soon as they could speak English,
they learned to swear; but if he had more of my company, I would teach him better;
and wished he was a Quaker, then he would not swear.
Afterwards I visited their king, who was a very solid man:
he would not be satisfied until I sat down at his right hand.
I had some discourse with him about religion: he was very willing to hear me,
and showed what respect he could;
and offered me such entertainment as his house afforded, which was a cup of water.
When I was about to go away, he signified his satisfaction,
being well pleased with my visit.

Then I visited several meetings in Chester county,
where many who had run out with George Keith into separation, came.
I was enabled to open the principles of Truth,
and vindicate our ancient testimony concerning our faith in Jesus Christ;
declaring to them that we believed in him as being the only begotten Son of God;
who in the fulness of time, took flesh, became perfect man, according to the flesh;
descended and came of the seed of Abraham and David,
but was miraculously conceived by the Holy Ghost, and born of the Virgin Mary;
yet powerfully owned to be the Son of God, according to the spirit of sanctification,
by the resurrection from the dead: and that as man, Christ died for our sins, rose again,
and was received up into glory in the heavens; having fulfilled the law and the prophets,
and put an end to the first priesthood, is a priest for ever,
not after the order of Aaron, but of Melchisedec;
and ever lives to make intercession to his Father, not for our sins only,
but for the sins of the whole world:
so declared our faith to be firm in Christ our heavenly Head;
and that many had suffered deeply, because they durst not break his commands.
The Lord's power and presence was witnessed in our assemblies; and our hearts were bowed,
and filled with praises to his worthy name.
Several of them who had run out with George Keith, were reached by the Lord's power;
and being prevailed upon by his love, confessed to the Truth,
and said it was sound doctrine.
Those who were lifted up in their imaginations, came flatteringly to me, and told me,
'They were glad I was sound in the faith; for what I had declared,
a great many had denied:'--I bid them name one; but they could not.
So being silent,
I told them 'I had had the opportunity of seeing
most of the people called Quakers in the world,
and never yet met with one, that was owned by them, that denied it;
and I knew it was the faith of the Quakers the world over: and that George Keith,
and those who were gone into separation with him, had given way to a lying spirit,
and falsely declared to the world we denied the man Christ Jesus:
and except they did repent, they would wither, die, and come to nothing;
for the charge against us was false.'
Some of them replied, I would never see that day:--I told them,
'I had seen it in the light of the Lord, at their first running out, and was made.
to warn them of it;' so we parted.

I went to Haverfordwest, where the Welsh people dwelt, and found a tender-hearted people:
several Friends from Philadelphia met me there;
and the Lord's power comforted our hearts, and filled them with joy and gladness.
Afterwards we went to the city, where I staid some time, and found Friends alive to God,
and in sweet unity one with another;
but several of those who had run out into separation were restless, tossed to and fro,
unstable as water, being gone from Christ, the true fountain of light and life,
into imaginations; so were stumbling, and falling,
and getting themselves dipped in water.
I could not but mourn for them, being sensible of their great loss;
seeing them to be in an exalted mind,
vainly lifted up above the simplicity of the
Truth in the conceit of their high attainments.
Several Friends visited them in love; but they reviled them,
and rejected the Lord's mercies.
I found the Lord's power and presence to be
greatly manifested amongst Friends in that place.

From thence I went to Germantown, and had a meeting,
to which many of the Separatists came; several of whom had been dipped in water.
After the meeting, they began to cavil; but the Lord's power came over them,
which chained them down.
Then I travelled into the county of Bucks,
and declared the way of life and salvation unto the people.
Thence to the yearly meeting at Burlington: many Friends from East and West Jersey,
and Pennsylvania, were there.
Friends in the ministry had a meeting together, wherein the Lord's power overshadowed us,
causing our cups to overflow:
we were engaged to encourage one another to faithfulness to
Him who had called us with such a high and honourable calling.
The yearly meeting was large; the Lord's power wonderfully broke in upon us,
so that many living testimonies were borne from the motion of the spirit of Truth,
and hearts filled with praises to the dreadful name of the Lord.
The meeting lasted four days, and Friends were kept in the peaceable spirit of Christ:
the affairs of the church were sweetly carried on, and managed in God's fear and wisdom,
in which we were a true strength one to another.
Although several of the Separatists came,
and made a jumble and disturbance when we were
performing our religious worship to Almighty God,
yet Friends kept their places, and went on in their testimonies;
and the Lord's power came over all.

Some of the Separatists were so wicked, that they uttered many blasphemous words;
and while I was declaring the way of life and salvation,
directing all to the light of Christ Jesus,
they lifted up their voices till their faces turned black; and told me,
The light I spoke of was nothing but an idol, and a frozen light;
with many more such like absurd expressions.
But I told them.
It was no other but Christ Jesus the true light,
which lighteth every man that cometh into the world, as John declared,--John 1: 9;
and it was the testimony God had given us to bear;
and the business we were sent about was,
to labour to turn people's minds from darkness to this true light,
and from satan's power to the power of God;
that people might come to receive remission of sins by faith in Christ Jesus;
to which light, all the nations of them that are saved must turn and walk in;
it was the apostle's treasure, and so it is every true believer's now.
When they had wearied themselves, they went away;
after which we had a heavenly conclusion, and parted in peace.

Then finding drawings in my mind to go to the yearly meeting in Maryland,
I went in company with several Friends.
We travelled hard, and reached the meeting the day it began, visiting meetings as we went.
There being a great fleet of ships lying not far distant,
abundance of people came to the meeting, both merchants, captains of vessels,
and many others of divers ranks and persuasions.
The merchants and captains were very sober; but several others behaved very rudely,
talking, and smoking tobacco: the power of Truth and the testimony thereof, reached them;
so that those rude people were much ashamed of their behaviour,
and crowded into the meeting-house till it was filled:
and the Lord caused his everlasting gospel to be
proclaimed in the demonstration of his power and wisdom,
which did plentifully flow amongst us; and we witnessed that Scripture to be fulfilled;
"`He maketh his angels spirits, and his ministers a flame of fire.`"
The hearts of the faithful were made truly glad;
and dread and terror took hold of the rebellious.
It proved a day of visitation to many;
for the Lord made his instruments as clouds full of rain,
and caused them to empty themselves amongst his heritage.
The affairs of the church were managed in God's fear and wisdom:
nothing appeared but love and unity among Friends.
The meeting held four days;
and ended with praises and thanksgiving unto the God and Father of all our mercies, who,
with his dear Son, is worthy thereof.

After the meeting, we returned to Chester and the head of Chesapeak bay,
and visited Friends and others.
We found great openness in the hearts of many to receive Truth's testimony;
and several were tendered and reached thereby.
Then we travelled into Pennsylvania, and had several meetings in the lower counties,
travelling very hard;
for I was pressed in spirit to go to the yearly meeting at Shrewsbury,
having several meetings to visit as I went.

When I was at Philadelphia, a great exercise fell upon me for the West India islands,
viz. Barbadoes, Antigua, Nevis, and Jamaica;
under which I travelled in free resignation of mind to answer the will of God:
for I had a sense of an evil spirit which was at work in those western isles,
in order to hurt God's heritage, by drawing them from the power of Christ.
As I kept the word of patience, and my mind single to the Lord,
waiting to know his mind therein, it came upon me to write;
and early in the morning I wrote an Epistle,
and caused several copies to be taken and sent to the said islands,
whereby I got ease of mind.
The Epistle is as follows:

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

I am moved of the Lord, in the motion of life, to send you these following lines;
being deeply bound under the sense of the love of God in visiting us,
and making his way and Truth known to us,
and in gathering us to be a people that were no people,
and bringing of us to worship him, who is a Spirit, in spirit and in truth;
where we have known the streams of love and life to run,
in which our souls have found true pleasure.
As our minds came to be staid upon the Lord, our peace flowed,
and our love increased to him and to one another; which brought us to be of one mind,
and often filled our hearts with praises to his most worthy name.

Now, Friends, my spirit is engaged in the motion of life, to caution, warn,
and charge you all to keep to God's power that first gathered you;
that by it you may be preserved low in his fear,
with your minds purely staid in the light of the Lord Jesus Christ;
unto which you have been turned, and by which you have come to the knowledge of God,
and Jesus Christ his Son, whom to know is life eternal.
Now, as you have received the Lord Jesus Christ, be careful to walk in him;
in whom you have life, peace, and salvation,
and from whom you are to receive daily nourishment to your souls;
and witness the cross of Christ, which is the power of God,
to crucify you to the world and the world unto you;
so that thereby you may escape the corruptions that are in the world through lust,
and be made partakers of his divine nature.
By the virtue thereof you will be made to bear witness against the world,
and all its ways, customs, fashions, notions, and false ways of worship that are therein;
and stand up for your holy way, Christ Jesus, the true light,
that "`enlighteneth every man that cometh into the world.`"
And as in him you all walk, and know the virtue of his power every day to strengthen you,
in the dominion of his life, power, and wisdom,
you will stand in your testimonies against all that rise up against him;
and be of those that are following the Lamb through many tribulations;
and live to God over all, to his glory and your comfort.

Now, as it was God's power that gathered you, so it is the devil's work to scatter you,
and drive you from the true foundation, Christ Jesus the true light.
I say, all walk in him, and wait in his light,
where you will have the great mystery of godliness more and more revealed unto you;
and so see over and through the mystery of iniquity and the devices of satan,
his sly insinuations, lies and prevarications, which he is possessing many with;
making them instruments in his hand to trouble the churches of Christ,
and to make rents and schisms therein; dividing in Jacob, and scattering in Israel.

Therefore watch against the enemy's working in the mystery,
though with never so large pretences and fair shows:
his work is still to draw away the mind from the pure conduct of the spirit of Truth,
into high conceits and imaginations, and so into separation from God and his people.
I warn you all to watch and keep low, that the enemy may not gain ground upon you,
nor draw your minds from the simplicity of the Truth;
but that you may feel the Lord daily to break your hearts, and tender your spirits,
and give you a clear discerning between that
which serveth God and that which serveth him not,
both in yourselves and others.
So will you have a sense and feeling beyond words;
and never be deceived by the fair words or pharisaical
carriage of any whose spirits are wrong,
and are gone into contention and strife; making rents and divisions in the church:
such labour to gather to themselves and not to Christ.
Experience hath showed the work of that spirit in former ages,
(as also in this age) and what hath been the end of those that have been led by it.

Therefore all keep to the Lord's power,
and thereby you will be preserved out of the snares of the enemy,
and firm in your testimony against that spirit of strife and contention:
touch not with it, but live over it; for all that join with it, will wither and die,
and come to nought.
It is the word of the Lord God as a warning to you all, to watch against,
and feed it with judgment wherever it appears.
Though it may appear as Saul did, to bless the true prophet of the Lord,
yet it is that which is gone into rebellion against God, and doth not obey him.
And though those who are gone into this spirit,
may strive to be honoured before the people,
(as Saul did,) and may be rending and tearing to obtain honour,
yet the Lord will rend the kingdom out of the hands of those that join with it,
although they may have known something of the anointing oil,
and have been anointed therewith.
It is those that keep in obedience to Christ,
that shall be made partakers of the benefits of his obedience to his Father;
for it is said of him,
"`He became the author of eternal salvation to all them that obey him.`"
So mind your obedience unto him; and then you will all know of his doctrine,
which drops as the dew upon his tender heritage; blessed be his name for ever.

Now, 'Seeing it is a righteous thing with God,' saith the apostle,
2 Thessalonians 1:6. 8,
'to recompense tribulation to them that trouble you: and to you who are troubled,
rest with us, when the Lord Jesus shall be revealed in flaming fire,
taking vengeance on them that know not God,
and that obey not the gospel of our Lord Jesus
Christ:' therefore mind your rest in Christ,
and keep in it; and obey his gospel, and keep to his doctrine, which is,
'Have salt in yourselves, and have peace one with another;' also the apostle saith,
'If any man seem to be contentious, we have no such custom,
neither the churches of Christ.'
So all keep to the eternal power of God, and you will be kept out of evil by it.
In the pure love of Christ my soul salutes you all; desiring grace, mercy, and peace,
may be multiplied amongst you, and all the churches of Christ the whole world over:
letting you know that my dear companion Thomas
Wilson was well the last time I heard from him.
We have had little rest since we were with you,
but have been labouring in the work of the gospel.
His dear love was to you all, and so doth mine remain; and I send this,
as a token thereof, in obedience to the Lord;
in whom I remain your friend and brother in tribulations and patience,

[.signed-section-signature]
James Dickinson.

[.signed-section-context-close]
Philadelphia, the 17th of the Eighth month, 1696.

[.signed-section-context-close]
Let copies of this be sent to Antigua, Nevis, and Jamaica, to be read in their meetings.

--

I proceeded into West Jersey, and had several meetings; then travelled,
in company with several Friends, through the woods to East Jersey,
to the yearly meeting at Shrewsbury,
which began the 24th of the eighth month and held four days.
We laboured to stir up Friends to faithfulness;
directing all to Christ the true foundation;
that thereby they might know his power to subject their spirits,
and lead them into all Truth, both in doctrine and discipline.

The Lord eminently appeared amongst us to our comfort,
and we were sweetly refreshed together in the enjoyment of his love.

After the meeting, several Friends went with me towards New York.
We crossed Amboy ferry in two canoes,
which the watermen lashed together to carry us and our horses over,
and staid at Amboy that night.
Next day we went to Elizabeth-town, took boat for New York,
and were all night upon the water, exposed to wind and storms: it rained all night,
and we had no shelter; for the boat was filled with wood, and we sat upon it.
About break of day, we got to New York, where we staid a little;
then passed over in a canoe to Long Island, and travelled up and down in that island,
labouring in the work of the gospel; and had good service for the Truth.
Several were convinced, particularly a captain in the army and a justice of the peace,
who were afterwards called before the governor of New York:
and because they could neither swear nor fight any longer,
they laid down their commissions, having received the Truth in the love of it;
which was cause of gladness to us;
for we had no greater joy than to behold the Lord's
work to prosper in the hearts of the children of men.

Being clear of Long Island, we returned to New York, where we had a large meeting;
in which we opened the principles of Truth,
by and through the demonstration and power of God,
and wiped off the reproaches which George Keith, and those who ran out with him,
had cast upon us.
Many hearts were deeply affected and tendered, both among the Dutch and English;
and the Lord's power was over all.
Near the conclusion of the meeting, William Bradford,
(who had printed several books which George Keith and others wrote against Friends),
began to make disturbance; and flatteringly said,
He was glad to hear the doctrine which was delivered that day:
notwithstanding he would vindicate what they had written and printed.
I saw if we entered into debate, it would draw people's minds out,
which were measurably turned to the Lord's power, and reached thereby:
then it was upon me to supplicate the Lord in prayer.
After I had done, a Friend stood up, and declared among the people, that George Keith,
and those who had written and accused us with denying the manhood of Christ,
had wronged themselves and us too; for he knew not one that was a Quaker,
that ever denied the manhood of Christ; and farther said,
'We believe there is one Mediator between God and man, even the man Christ Jesus;
and by no other name but that of Jesus, we expect salvation;
and by his Spirit we must be adopted,
and made heirs of that peace and rest he hath purchased
for us with the price of his precious blood;
by which we shall be changed if we walk in the light, as he is in the light,
wherein our true fellowship doth consist.'
People seemed generally dissatisfied with
Bradford's appearance in so disturbing a manner;
for the Lord's power was over every unclean spirit,
and the testimony of Truth exalted over all: so the meeting ended.

Having appointed a meeting at Chester next day, we sailed several miles in canoes,
and through much difficulty got to the meeting, which was to satisfaction.
Then we returned to Long Island, and in our passage over, the wind rose,
and water came into the canoes: we sat deep in it,
for none durst move to cast it forth for fear of oversetting,
although it was frost and very cold weather:
yet after much difficulty and fatigue we got safe to land.
Being clear of those parts, we returned to New York,
took boat and passed over to East Jersey:
then travelled through the woods to West Jersey, so to Burlington and Philadelphia;
and had good service for the Truth.
It being frost and a great snow, it was very tedious travelling;
yet the Lord made way for us both inwardly and outwardly,
and made hard things easy to us.

We visited the sick and aged in our travels,
and sympathised with them in their afflictions:
the Lord's power reached unto them and helped them,
and they were comforted in their exercises.
We travelled through the woods to Salem,
(many Friends accompanying us,) and had several meetings thereabouts.
At Cohansey, abundance of professors came to the meeting;
the gospel was preached to them, and many were deeply affected:
we were concerned to vindicate and lay open our principles,
for the clearing of the reproaches cast upon them by those who were gone out from us.
The Lord's power came over all, and we returned in great peace;
witnessing that saying to be fulfilled,
"`Great peace have they which love thy law.`"--Ps.
119:165. We had several meetings in Philadelphia;
and that ranting spirit which laboured to lay waste,
and hinder the growth and prosperity of the Truth, was chained down by the power of God;
our assemblies were filled with his love, and our hearts drawn near him.
After the meetings, several of those who had gone out from us, began to cavil;
and would have made me an offender for a word, which, they said, I had spoken.

But I saw their life was in jangling,
and remembered our blessed Lord and Master's example, who, when he was accused,
answered not a word; having regard to the honour of God,
not to make our solemn assemblies a place of contention:
for I had seen their behaviour at a meeting before, several of them speaking at once.
So I took little notice of them, knowing that God is not the author of confusion,
but of peace and love.
In the sense of his love we travelled and laboured to turn
people's minds to Christ the true Rock and Foundation,
and to keep our consciences pure from the blood of all men.
The Lord was with us, and fitted us for our service every day;
and the angel of his presence attended his people,
and drew them near to himself and one another;
in which nearness our hearts were bound up with them.
For though the power of darkness had been greatly at work to
scatter and lay waste God's heritage in those parts;
and had prevailed upon some,
who had not been careful to watch in the light of Christ Jesus,
but were drawn from the simplicity of the gospel into strife and contention,
and a disposition to accuse their brethren;
yet we found the Lord's power to be much at work in settling
and establishing those who kept their minds close to him;
so that many came to witness that saying fulfilled,
"`Thou wilt keep him in perfect peace, whose mind is staid on thee,
because he trusteth in thee.`"--Isa. 26:3. For we found them, to our great comfort,
in a growing condition, and in unity one with another.

Being clear of those parts, we took our journey towards Maryland,
having several meetings in our way.
At Darby, we met with Henry Payton and his sister,^
footnote:[Henry Payton resided at Dudley, in Worcestershire.
His daughter, Catharine Phillips, in an account of him prefixed to her Journal says;
"`He was called into the work of the ministry about the eighteenth year of his age;
and when young, travelled much in the service of Truth in divers parts of this nation,
Ireland and Scotland, as also the American colonies.
His ministry was lively and clear;
and his care not to exceed the openings of Truth therein, apparent.
His deportment was grave, his conduct clean and steady, and his charity,
in proportion to his circumstances, diffusive.
He was an affectionate husband, a tender father and kind master;
serviceable amongst his neighbours, and beloved and respected by them.
He died in the year 1746, aged nearly 75 years.`"
{footnote-paragraph-split}
His sister, "`Sarah Payton,
was born at Dudley +++[+++aforesaid,+++]+++
and received a gift in the ministry when about twenty-one years of age;
in the exercise of which, she laboured not only at home and in Ireland,
but also in America, previous to her marriage with Samuel Baker,
an honest Friend of Dublin.
She resided in that city for the most part of the remainder of her life;
and was very serviceable to Truth and Friends in many respects;
being a diligent labourer and fellow-helper with her brethren in the gospel:
and in the authority of Christ Jesus did freely and frequently,
in larger and lesser assemblies,
preach and teach the things concerning the kingdom of God,
and the redemption that is in his Son, Christ Jesus.
She had also good service in women's meetings, being a diligent follower of good works,
in relieving the poor and visiting the sick and afflicted in body or mind.
When outward strength declined, her inward strength was renewed; her lamp being trimmed,
did burn clearly, through the supply of heavenly oil, to the conclusion of her time;
and at her departure she had the comfort of an evidence of peace with the Lord,
and that a crown of righteousness was laid up for her.
She died in the year 1713.`"--Rutty's _History of Friends in Ireland._]
who were come out of England on Truth's service:
they went back with us to several meetings,
and the glory of the Lord overshadowed us to our comfort.

At Concord, where was held the last meeting we had in the province of Pennsylvania,
the Lord crowned our assembly, and filled our hearts with his love;
so that tears of joy flowed from most of us,
and we were enabled to offer up praises unto the God and Father of all our mercies.

After the meeting, we parted with them in much bowed-downness of spirit,
under a sense-of the Lord's goodness, and went on our journey towards Maryland:
we travelled very hard for three days, before we got among Friends where our service lay.
The ground was covered so thick with snow,
that few had ever seen the like in those parts; which made our travels more difficult.
Then we proceeded to Choptank, and visited Friends on the eastern shore;
afterwards crossed Chesapeak-bay to the western shore,
where we had several comfortable meetings.

When we were clear of those parts, it was upon us to go to Virginia and Carolina.
A master of a ship that lay in Patuxent river took his boat and put us over the river,
travelled along with us to Potomac, and went over that river,
which was nine miles across.
It was night, and we all strangers to the place: seeing a boat at a distance,
we came up with her, and got her to pilot us to a plantation on the shore,
where was a captain's house: they lived very poorly,
having nothing to eat or drink but pone^
footnote:[A kind of Indian bread.]
and water; but they were willing to entertain us with such as they had.
Next morning, we got horses, and hired a guide to Rappahannock river,
where many ships lay; hoping to get over in some of their boats:
but there came on such a strong north-wester that the people
were afraid it would have blown down their houses;
insomuch that we were forced to run out into the storm, which was very violent.
After it was a little abated,
it froze so hard that we could not get over the river for a whole week.

During our stay, we had disputes with several, and opened the principles of Truth to them.
One major Taylor confessed to the Truth, and said.
If the Quakers' principles were such as we declared, he was a Quaker in judgment;
but desired to have more time with me, to be informed why we left the Church of England.
I told him.
The Church of England had the form of godliness, but denied the power;
and from such the apostle advised to turn away: and they maintained tithes,
which belonged to the Levitical priesthood,
which we believe Christ came to put an end to: and their ministers preach for hire,
and divine for money; cry peace to the people while they put into their mouths,
but when they withhold, prepare war against them: they indeed profess good things,
but do not practice them, and say and do not; unto such Christ cried,
"`Wo!`"--He answered, What I said was true; but said, 'Our principles are good;
though it is a great shame to us that our ministers are so wicked,'--I told him,
'We must judge of the tree by its fruit, according to Christ's own doctrine:'--he said.
It was very true; and seemed fully satisfied concerning our principles.

As soon as we could, we passed over the river,
and travelled through the woods to Mattapony, where a friendly man dwelt,
with whom we staid two days, and had a meeting at his house:
many had the opportunity of hearing the gospel preached,
and God's universal love proclaimed, which was glad tidings to their poor souls:
many hearts were deeply affected by the Lord's power,
and ours were bowed under a sense of his goodness to the children of men.
After that meeting, several desired to have another;
but we being pretty much pressed in spirit to visit some other parts of Virginia,
and Carolina, proceeded on our journey.
The next day we heard of one John Carver, who made a profession of Truth,
but had seldom been at any of our meetings: we travelled to his house,
as it was not above ten miles out of our way, and found the man much in imaginations,
conceits, and notions: we were much burthened in our minds with him.

Next day we travelled towards Ware river, where the ship lay,
in which we intended to take our passage for England: the day following we got on board,
and staid some days.
The people thereabouts being very desirous of having a meeting, one Sampson Dorill,
a lawyer, gave us liberty to have one at his house.
Abundance of people came,
it being the first Quakers' meeting that had been in those parts:
the Lord appeared in his love,
and touched our tongues as with a live coal from his heavenly altar,
and loosed them to declare of his mercies to those that
would return at the reproofs of wisdom,
and lay hold of the day of their visitation.
Many hearts were reached, and several desired we would stay there and have more meetings:
but having some further service to perform in visiting Friends,
we took our journey towards Carolina;
and got two negroes to carry us over York river in a small boat.
The wind arose, so that we could not get the negroes to set us to the place intended;
but they put us ashore at the first land they could get.
As it was near night and there was hard frost and snow,
we travelled almost till midnight before we got to a plantation;
having our saddles and bags to carry.
Next morning we got to Edward Thomas's and had a meeting; then crossed James river,
travelled to Pagan's creek and Chuckatuck, and visited meetings as we went:
so through the wilderness to Carolina, and there met with governor Archdale,
who travelled through Carolina with us.
We had good service in that wilderness country,
and found a tender people who were glad to be visited.
Being clear, we returned in peace, and attended the shipping for England.
The fleet staying some time,
we visited several places as we found an openness in
people's hearts to receive the testimony of Truth;
directing them to Christ, the true foundation.
The Lord was effectually with us, to our great comfort;
and having in ourselves the answer of well done,
our souls were filled with praises to his most holy name, who is God, blessed for ever.

On the 7th of the third month, 1697, we set sail from the Capes of Virginia,
being about one hundred and thirty sail in company.
In the ship that I came in, there were several Friends; one, whose name was Hugh Roberts,
had the testimony of Truth to declare, and was coming to visit Friends in England:
we had three meetings every week during our voyage.
After we had been a week at sea, we met with a great storm,
and were in danger to have run down one another.
The man-of-war lay by, and caused all the fleet to lay to, under their mainsails,
all night.
There came a ship which had like to have run foul of us;
but we backed our mainsail and got clear.
The storm was so violent that it split our mainsail;
and before we could get the yard lowered, it had like to have been carried away:
the ship also sprung a leak,
so that we were forced to keep the pumps going day and night for two weeks.

When the storm was over, and the sea calm, we stitched an old sail full of oakum,
let it down under the ship, and undergird her; and after some time, the leak stopped.
When the ship came to be searched, it was found to be an auger hole half open,
and the other filled with something that had got into it.
After five week's sail we met with a vessel that had been taken by the French:
she gave us an account that there was a French fleet out at sea, waiting for us;
so we kept to the southward,
and almost run out our longitude before we got into our latitude, and escaped them.
When we had been six weeks at sea, we made the isle of Scilly: the day after which,
several great ships of war met us, in order to convey us up to London;
but the wind being contrary, we were forced into Plymouth,
and landed there on the 22nd of the fourth month:
having had many refreshing seasons in the love of God, when on the deep ocean.
The consideration of the Lord's dealings with us,
in protecting us both inwardly and outwardly, bowed my mind in true thankfulness,
and made me say, that he was worthy to be followed and obeyed in all his requirings.

The day after we landed, we had a large and comfortable meeting at Plymouth.
The next day we took our journey towards Exeter, and were at their first-day's meeting.
From thence we travelled to Bristol, where I was taken very ill:
but in a week's time recovered, and had two meetings there;
after which I took my journey homeward,
William Penn and several other Friends accompanying me some miles.
I travelled hard, got well home, and found my wife and family well;
which deeply bowed my spirit before the Lord,
under the consideration of his tender dealings with me every way,
and giving me my life for a prey.
Though one may go forth weeping, bearing precious seed,
I knew a returning as with sheaves in my bosom; blessed be the Lord,
who is the Preserver of all those that put their trust in him.
